### ISSUE TITLE
Revoking non-existent Grant Option breaks MySQL 5.6 Replication

### ISSUE THREAD

**Issue by pma-import** [phpmyadmin/phpmyadmin#10435]
This applies to MySQL 5.6.

phpMyAdmin removes the grant option by default if you modify user rights even if there is no grant option defined for that user, so Replication always breaks if you use phpMyAdmin to modify user rights for a certain table on which the user has no grant option.

Replication also breaks if you revoke the grant option from a database or table if the grant is not defined.

mysql> REVOKE GRANT OPTION ON `testdb`.`test_table` FROM 'testuser'@'127.0.0.1';
ERROR 1141 (42000): There is no such grant defined for user 'testuser' on host '127.0.0.1'

Leads to a "Incident: LOST_EVENTS"-Entry in binary log and makes the slaves stop.

Applies to all phpMyAdmin-Versions i suppose. Tested in 3.3.10.2 and 4.0.5. 

According MySQL-Bug: http://bugs.mysql.com/bug.php?id=68892

phpMyAdmin should only execute "revoke grant option" if the user has a grant option on that table. 

---
* **Original URL**: https://sourceforge.net/p/phpmyadmin/bugs/4052/
* **Original author**: moritzschuepp
* **Found in version**: 4.0.5

**Comment by madhuracj** [comment]
Looks like this has been fixed in later version of MySQL as I am unable to recreate the issue with MySQL 5.6.17.

**Comment by madhuracj** [comment]
From http://bugs.mysql.com/bug.php?id=68892, "Fixed in 5.6+. Documented fix in the 5.6.15 and 5.7.3 changelogs".
Since this is more of a bug in MySQL and there is a fix available I prefer to close this.

**Comment by SvenMW** [comment]
This is not fixed, this is still present in latest 5.6
Please note that the upstream bug in mysql is "closed" not in "fixed" state.
This is actually expected behaviour of mysql, the "fix" (on the mysql side) is to add documentation for this behaviour and how to heal your replication once it is broken.

The correct way to fix this is to not revoke grants which where never given to the user.

Please reopen, thanks.
