### ISSUE TITLE
PHP gettext warnings related to PHP 7

### ISSUE THREAD

**Issue by robert-scheck** [phpmyadmin/phpmyadmin#11462]
Using phpMyAdmin 4.4.14 (from Fedora) with PHP 7.0.0 RC1 the login page already throws this:

**Deprecation Notice** in ./../php/gettext/streams.php#48
Methods with the same name as their class will not be constructors in a future version of PHP; StringReader has a deprecated constructor

**Backtrace**

./../php/gettext/gettext.inc#41: require()
./libraries/select_lang.lib.php#477: require_once(./../php/gettext/gettext.inc)
./libraries/common.inc.php#563: require(./libraries/select_lang.lib.php)
./index.php#12: require_once(./libraries/common.inc.php)"

Note that PHP gettext is unbundled at Fedora, however I was not able to see that the bundled PHP gettext in phpMyAdmin would contain a fix for that. If I am wrong, please let me know (and I am happy to backport a fix to Fedora/EPEL packages).

**Comment by robert-scheck** [comment]
* StringReader has a deprecated constructor
 * FileReader has a deprecated constructor
 * CachedFileReader has a deprecated constructor
 * gettext_reader has a deprecated constructor

**Comment by lem9** [comment]
Robert,
the bundled php-gettext works fine under PHP 7, see https://github.com/phpmyadmin/phpmyadmin/issues/11387

**Comment by robert-scheck** [comment]
Marc, is this f15f67e60423...1ad1a3846b79 which I would have to backport to the system RPM (php-php-gettext)?

**Comment by lem9** [comment]
Robert, sorry I gave you a reference about a different library in my previous comment. In phpMyAdmin 4.4.3 we fixed php-gettext for PHP 7 compatibility, see 77369e5e.

**Comment by robert-scheck** [comment]
Marc, thank you for the explanation. I added your patch to the Fedora/EPEL RPM packages at https://bodhi.fedoraproject.org/updates/?like=php-php-gettext-1.0.11-12 in case somebody is using SCL or RHSCL (to achieve a newer PHP version on a current release).

**Comment by enoch85** [comment]
I still see this in Ubuntu 16.04 (php 7 and mysql 5.7)

```
Deprecation Notice in ./../php/php-gettext/streams.php#84
 Methods with the same name as their class will not be constructors in a future version of PHP; FileReader has a deprecated constructor

Backtrace

./../php/php-gettext/gettext.inc#41: require()
./libraries/select_lang.lib.php#477: require_once(./../php/php-gettext/gettext.inc)
./libraries/common.inc.php#569: require(./libraries/select_lang.lib.php)
./db_structure.php#13: require_once(./libraries/common.inc.php)
``` 

cc @lem9

**Comment by gewaechshaus** [comment]
same here @enoch85

**Comment by WillPresley** [comment]
@enoch85 @gewaechshaus While not the optimal solution, I was seeing the same issues on Ubuntu 16.04 and adding this (fairly well trusted) PPA and then upgrading PHPMyAdmin to the latest version available fixed it for me: https://launchpad.net/~nijel/+archive/ubuntu/phpmyadmin
`sudo add-apt-repository ppa:nijel/phpmyadmin`

It will at least take care of the issue until the packages in the Ubuntu repos are built again.

**Comment by gewaechshaus** [comment]
@WillPresley - big thx! We're using Ubuntu 16.04 to...

**Comment by kimwue** [comment]
@WillPresley  thanks for the suggestion, but for me this didn't change anything. Still receiving those deprecation erros.

**Comment by daveteu** [comment]
instead of going all over to find new package, actually it's just 4 line to edit and it doesn't change the functionality of the codes at all.

http://askubuntu.com/questions/796135/depreciation-notice-error-in-phpmyadmin-with-16-04/796705#796705

**Comment by srandolph** [comment]
@daveteu - Every time we get in the weeds and look around it makes us understand a little bit better.  This worked and it was the easy solution.

**Comment by sinanisler** [comment]
yeah for now 
`add-apt-repository ppa:nijel/phpmyadmin`
fix my problem too thanks @WillPresley

**Comment by tebaly** [comment]
similar problem. install by ansible - fail
_repository ppa:nijel/phpmyadmin_

> Depends: php-php-gettext but it is not installable or php-gettext (<= 1.0.11-2) 

But: php-gettext is already the newest version (1.0.11-2**build1**) 

To fix installation, i remove _repository ppa:nijel/phpmyadmin_

**Comment by tufahu** [comment]
i've added `php_value error_reporting 6135` to /etc/apache2/conf-enabled/phpmyadmin.conf

**Comment by AntoscencoVladimir** [comment]
@WillPresley Thanks, works ! LinuxMint 18 sarah

**Comment by dandyxu** [comment]
@daveteu The issue is fixed perfectly! Thank you very much.

There is a mistake in the answer, the error is happened in the file streams.php, not gettext.php.

So you should edit the code in the file /usr/share/php/php-gettext/streams.php

All the rest of the answer are accurate and ok to use.

Thanks.

**Comment by wojcikm** [comment]
@daveteu Thank you very much for this solution. For me was to change a 4 constructors, but still much better solution than interfere with the system itself.

**Comment by Redshoee** [comment]
After  `sudo add-apt-repository ppa:nijel/phpmyadmin`
restart the apache2 and it works
thanks

**Comment by archergod** [comment]
Though I see we can avoid this error by installing phpMyAdmin from ppa or changing file ourselves, but is there a place where default ubuntu 16.04 repo use latest version instead of 4.5.4 ? I see 4.7 is out but ubuntu is still giving 4.5.4 which has this issue. I prefer to go offficial channels on server, and hence seeking to solve it that way.

**Comment by trnguyenvan** [comment]
@WillPresley : It's work for me. Thanks alot.

**Comment by williamdes** [comment]
I updated some comments because the PPA location changed
https://github.com/phpmyadmin/phpmyadmin/issues/15515#issuecomment-548521407

**Comment by WillPresley** [comment]
@williamdes Cheers for that!
