### ISSUE TITLE
Incorrect syntax creating an user using mysql_native_password with MariaDB

### ISSUE THREAD

**Issue by hurrycaner** [phpmyadmin/phpmyadmin#11520]
According to MariaDB docs (https://mariadb.com/kb/en/mariadb/development-pluggable-authentication/), the correct syntax to create an user with mysql_native_password plugin is:
```
CREATE USER asd IDENTIFIED VIA mysql_native_password USING '***';
```
And today phpMyAdmin 4.5.0.2 is using this syntax:
```
CREATE USER 'asd'@'%' IDENTIFIED WITH mysql_native_password BY '***';
```

This is generating errors "1065 - Query was empty" error above the printed query and "The selected user was not found in the privilege table." right on top of the user creation wizard.

I was able to create the user directly in SQL Query with the syntax pointed at MariaDB docs. (got password hash using `select PASSWORD('test');`).

Versions:
phpMyAdmin 4.5.0.2
MariaDB 10.0.20-MariaDB

**Comment by devenbansod** [comment]
Looking into it.

**Comment by devenbansod** [comment]
Hi, thanks for the report.

I think this has been fixed in #11500 and the fix should be included in the 4.5.1 release.
For MariaDB, we are now using syntax like :
`CREATE USER 'test_mariadb'@'%';SET PASSWORD FOR 'test_mariadb'@'%' = PASSWORD('***');`

Please check here if it works [here] (http://demo.phpmyadmin.net/QA_4_5/) .

**Comment by mastacheata** [comment]
Is that really considered a fix?
I mean you didn't fix the MariaDB vs MySQL syntax difference, but simply remove the pluggable authentication if the Database System is MariaDB.
Wouldn't it be better to adjust the syntax for MariaDB instead of removing the authentication plugin part completely?

**Comment by devenbansod** [comment]
@mastacheata : Sorry that I did not realize it before. Thanks for pointing that out.
I did not realize that user could have independent pluggable auth plugins as well and not only the 2 always-supported plugins.
Add so, yes. Adjusting to MariaDb syntax seems more correct. I will put in a pull request soon to fix it.

**Comment by devenbansod** [comment]
Please see : #11525

**Comment by AbbyNormal** [comment]
Hi,

there is a bug for this. If you create new user through phpmyadmin this is the syntax that is used:

CREATE USER 'test'@'localhost' IDENTIFIED VIA mysql_native_password USING '***';

And it works. But when you login with that username and change password it says changed but it really is not. If you logout and login with new password you will fail. You cannot login with new password but with old one you can.  This is shown in the log:

21:37:08 [Warning] 'user' entry 'test@localhost' has both a password and an authentication plugin specified. The password will be ignored.

If you delete in mysql.user of the user test field plugin, then new password is working. Any idea?
