### ISSUE TITLE
Error code: 200 when loading table's structure (Windows 10)

### ISSUE THREAD

**Issue by giuromano86** [phpmyadmin/phpmyadmin#11705]
When I view a table's structure, PMA gives me this error in a red popup:

> Error in Processing Request Error code: 200 Error text: OK

PhpMyAdmin version: 4.5.2
Windows 10 Pro 64bit
Apache 2.4.17 (Win32) 
PHP 5.6.14 
MySQL Community Server 5.7.9

I must refresh the page (f5) to get it works!

**Comment by lem9** [comment]
Can you reproduce this on http://demo.phpmyadmin.net ?

**Comment by giuromano86** [comment]
No, it works well on http://demo.phpmyadmin.net. It's strange, I just downloaded it without modify anything! I tried also to rename config-sample file to config.inc.php, without modify it, without success!

**Comment by mmiat** [comment]
me too, I've tried pma 4.5.2, 4.3.11 and 4.4.15.1
php 5.5
windows 7
if I modify session.use_trans_sid in php.ini, the first time I can see structure, after that error again

**Comment by Mesolo** [comment]
Got this too in 4.5.2
After some investigation (not able to reproduce on http://demo.phpmyadmin.net , maybe because is version 4.6 dev) i see that the problem is italian localization.
When i click on table structure link, in the console log i got this message: Invalid JSON!Unexpected end of input

Usually this is some unescaped charater somewhere. Changed the language in english and works OK.
Hope this helps

**Comment by lem9** [comment]
@Mesolo But on the demo server you can choose the latest stable version (currently 4.5.2). I tried 4.5.2 with Italian and could not reproduce this problem (Chrome 46), but I'm on a Linux server. Is your phpMyAdmin running on Windows 10 too?

**Comment by Mesolo** [comment]
@lem9 Yes i'm running latest stack of XAMPP (v. 5.6.15) on windows 10 64bit, Chrome 47 64bit
I manually upgraded phpmyadmin yesterday from 4.5.1 to 4.5.2 and found this issue after that.

**Comment by lem9** [comment]
@Mesolo Can you try running 4.5.2 from demo.phpmyadmin.net?

**Comment by Mesolo** [comment]
@lem9 Running from demo.phpmyadmin.net with italian language and version 4.5.2 working good, no issue found. 
Now i really have no idea what can produce this error.

**Comment by cipo28** [comment]
Same problem here but switching from Italian (not working) to English (working), then again to Italian it's working. Anyway I've noticed that if I create a new table it is possible to correctly see the structure instead of the older ones that's impossible.
I'm running PHPMyAdmin 4.5.1 on W10 64bit with XAMPP, browsing it with Firefox 42

**Comment by giuromano86** [comment]
Not for me. If I switch from Italian (not working) to English (working for me too), then again to Italian it's still not working!

**Comment by giuromano86** [comment]
In Firebug:
Invalid JSON!JSON.parse: unexpected end of data at line 1 column 1 of the JSON data

**Comment by Mesolo** [comment]
@giuromano86 Yes i have the same message. In fact the error is thrown because inside JSON.parse function is present an empty string, when must be a big json object (watching results with english language ajax calls)

**Comment by cipo28** [comment]
@giuromano86 I've edited my post yesterday: English-only for me too at the end

**Comment by bimbo1989** [comment]
Same problem for me with italian language.
Running Windows10 64bit, Chrome 47.0.2526.106 m, phpMyAdmin 4.5.2, manually updated.
Having phpMyAdmin language set to english seems to solve the issue.

**Comment by fstrazzante** [comment]
I've the same problem with italian language! I solved with F5 after clicked on Structure button. Or you can change to English language and it'll work!

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | SyntaxError
 Error Message |SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
 Exception Type |js
 Link | [Report#18108](https://reports.phpmyadmin.net/reports/view/18108)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](http://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | SyntaxError
 Error Message |SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
 Exception Type |js
 Link | [Report#17683](https://reports.phpmyadmin.net/reports/view/17683)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](http://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | SyntaxError
 Error Message |SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
 Exception Type |js
 Link | [Report#17231](https://reports.phpmyadmin.net/reports/view/17231)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](http://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | SyntaxError
 Error Message |SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
 Exception Type |js
 Link | [Report#15993](https://reports.phpmyadmin.net/reports/view/15993)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](http://reports.phpmyadmin.net).*

**Comment by nijel** [comment]
Can somebody please post JSON response which fails to be parsed?

**Comment by Mesolo** [comment]
@nijel In my case, it's just an empty string, that's why it fails

**Comment by giuromano86** [comment]
Same error with PMA 4.5.3.1

**Comment by UNIBS-Reds** [comment]
Same problem with Italian language in version 4.5.3.1.

**Comment by nijel** [comment]
Nothing in the PHP error log (if you enable error logging)?

**Comment by kevinoo** [comment]
This is my error in a red box (in the center of the page):

Errore nell'elaborazione della richiesta
Codice errore: 200
Messaggio errore: OK

The error in the console, it's same: "SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data". The response is an empty string.

I show this error only in Italian language, if I switch in english the error don't show.

My suggestion, if it can be helpful: in a my PHP project, this error is caused when in the response there is an encoding error (utf8 vs. latin1).

**Comment by Pes8** [comment]
Same issue here:

Windows 10 64 bit
Bitnami WAMP stack
PHP 5.6.17
PhpMyAdmin version: 4.5.2

If I switch to english the error disappear

**Comment by giuliolastra** [comment]
Same issue with italian Language (Error 200 while clicking on Structure)

Windows 10 64 bit
XAMPP
PHP 5.6.15
PhpMyAdmin version 4.5.1

**Comment by nijel** [comment]
Can somebody see this with phpMyAdmin 4.5.4 or newer?

If that is not the case it might be just another occurrence of #11783 and fixed in 
218f13d8e0de20c1d0f417d1792c8629f8d053e6.

**Comment by giuliolastra** [comment]
@nijel I've upgraded PhpMyAdmin to 4.5.4.1 the lastest version on https://www.phpmyadmin.net/ But the problem is still the same:

```
Errore nell'elaborazione della richiesta
Codice errore: 200
Messaggio errore: OK
```

**Comment by nijel** [comment]
Can you check PHP error logs if they indicate something?

**Comment by pierol** [comment]
Same error for me too:
Windows 7 SP1 x64
MySQL Server version: 5.6.28 
PHP version: 5.6.18
PHPMyAdmin Version information: 4.5.5.1 (up to date)
switching from Italian to English and it solves the problem.
I tried to log the php errors to a file but it didn't generate the file so i guess there aren't php error at all. Even from the Chrome Developer Console the ajax call return code is 200 but the response is empty:

Request URL:http://localhost/phpmyadmin/tbl_structure.php?db=ingegnosi.tennis.4.0&table=corso_allegato&token=31ca81daa25401fce8031025674a8fe9&ajax_request=true&ajax_page_request=true&_nocache=1457459434393655721
Request Method:GET
Status Code:200 OK
Remote Address:[::1]:80
Response Headers
view source
Cache-Control:no-store, no-cache, must-revalidate,  pre-check=0, post-check=0, max-age=0
Connection:Keep-Alive
Content-Encoding:gzip
Content-Length:25
Content-Type:application/json; charset=UTF-8
Date:Tue, 08 Mar 2016 17:50:34 GMT
Expires:Tue, 08 Mar 2016 09:50:35 -0800
Keep-Alive:timeout=5, max=98
Last-Modified:Tue, 08 Mar 2016 09:50:35 -0800
Pragma:no-cache
Server:Apache
Set-Cookie:pmaPass-1=WwazS5W8AMLiKAjA%2FGglKg%3D%3D; path=/phpmyadmin/; httponly
Set-Cookie:pmaUser-1=4LIGuDEVD8XTNAQOvaGeCg%3D%3D; expires=Thu, 07-Apr-2016 17:50:34 GMT; Max-Age=2592000; path=/phpmyadmin/; httponly
Set-Cookie:pma_iv-1=LDDkpGyka5YvrqRXk2sw0w%3D%3D; expires=Thu, 07-Apr-2016 17:50:34 GMT; Max-Age=2592000; path=/phpmyadmin/; httponly
Vary:Accept-Encoding
X-Content-Type-Options:nosniff
X-Frame-Options:SAMEORIGIN
X-ob_mode:1
X-Powered-By:PHP/5.6.18
Request Headers
view source
Accept:*/*
Accept-Encoding:gzip, deflate, sdch
Accept-Language:it-IT,it;q=0.8,en-US;q=0.6,en;q=0.4
Connection:keep-alive
Cookie:pmaCookieVer=4; pma_collation_connection=utf8_general_ci; pma_lang=it; phpMyAdmin=1jo1gqd7gtbtd563g9hr27c0q54hjbd7; pma_iv-1=t7bXaJk5VHrIcu7zTHO5%2BQ%3D%3D; pmaUser-1=AeQ0CHh2UM%2BMLROyjrTYuw%3D%3D; pmaPass-1=jzzHtKX9wm3%2BJqMehrf8aQ%3D%3D; pma_console_height=92; pma_console_config=%7B%22alwaysExpand%22%3Afalse%2C%22startHistory%22%3Afalse%2C%22currentQuery%22%3Atrue%2C%22enterExecutes%22%3Afalse%2C%22darkTheme%22%3Afalse%7D; pma_console_mode=collapse; IngegnosiConf={"imp":{"IdImpostazione":1,"NumeroGiorniVisibilitaWeb":7,"NumeroOreDisdettaPrenotazione":24,"SogliaDebitoBloccoUtente":100.0,"BloccaPrenotazioniOnline":false,"OraServizioLuce":"17:00:00","OraInizioPrenotazioni":"08:00:00","OraFinePrenotazioni":"22:00:00","NumeroPrenotazioniNellaSettimana":-1,"NumeroPrenotazioniMaxStessoGiorno":-1},"dateInit":"25/02/2016","dateMax":"03/03/2016","ruolo":"","culture":"it"}
Host:localhost
Referer:http://localhost/phpmyadmin/sql.php?server=1&db=ingegnosi.tennis.4.0&table=corso_allegato&pos=0&token=31ca81daa25401fce8031025674a8fe9
User-Agent:Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36
X-Requested-With:XMLHttpRequest
Query String Parameters
view source
view URL encoded
db:ingegnosi.tennis.4.0
table:corso_allegato
token:31ca81daa25401fce8031025674a8fe9
ajax_request:true
ajax_page_request:true
_nocache:1457459434393655721

**Comment by nijel** [comment]
Okay I've played a bit with this and the problem seems to be [here](https://github.com/phpmyadmin/phpmyadmin/blob/master/libraries/Index.php#L701):

```php
        $r .= '<th>' . __('Cardinality') . '</th>';
```

Adding additional ``x`` between "fixes" it:

```php
        $r .= '<th>' . __('Cardinality') . 'x</th>';
```
However I have still no clue **why** this fails at json encoding on Windows, but it looks like some strange PHP bug to me.

The translation also [doesn't look problematic](https://github.com/phpmyadmin/phpmyadmin/blob/master/po/it.po#L3801):

```po
#: libraries/Index.php:698 libraries/tracking.lib.php:991
msgid "Cardinality"
msgstr "Cardinalità"
```

**Comment by fstrazzante** [comment]
Could be 'à' of 'Cardinalità' ?

**Comment by nijel** [comment]
Yes it is, but that doesn't explain why adding x in between fixes it. This really seems like a PHP bug...

**Comment by nijel** [comment]
The problem is not the ``à`` itself, the problem is combination with ``</``. It makes the json module unable to decode it as utf-8 string. Calling mb_detect_encoding on the same string returns UTF-8...

I really ran out of ideas, so I've workarounded this problem, hopefully it won't appear again somewhere else. I've also added code to tell proper error message in this case, so that debugging it will be much easier (c964633).

**Comment by SirLogician** [comment]
For me the problem was $cfg['MaxRows'] setting. It was 500 for me and this was causing in big tables. I decreased it to 100, logged off, logged in and this cured the problem.

**Comment by giuromano86** [comment]
Version 4.6.0 fixed it!!! :D

**Comment by nijel** [comment]
Thanks for verifying my fix :-).

**Comment by cchauveau** [comment]
I, have the same error with french language

**Comment by LuigiMdg** [comment]
I have the same problema, Italian..
I solve temporally whit this sequence:
click on Struttura (structure), appear the message of error 200, cliick F5 (refresh) and the structure appear and work :)

**Comment by simone-omniaweb** [comment]
Problem still exists. Once switched to Italian, the problem persists even when switching back to english. Solved with the F5 (refresh) trick.

**Database server**

Server: localhost via TCP/IP
Server type: MariaDB
Server version: 10.1.10-MariaDB - mariadb.org binary distribution
Protocol version: 10
User: root@localhost
Server charset: UTF-8 Unicode (utf8)


**Web server**

Apache/2.4.17 (Win32) OpenSSL/1.0.2d PHP/5.6.19
Database client version: libmysql - mysqlnd 5.0.11-dev - 20120503 - $Id: 76b08b $
PHP extension: mysqliDocumentation curlDocumentation mbstringDocumentation
PHP version: 5.6.19


**phpMyAdmin**

Version information: 4.6.0 (up to date)

**Comment by zaiocrit** [comment]
i have the same error with 4.6.1 :(
if i click new table : error in process request
f5 do not resolve the problem :(

italian or english is the same

Database server

Server: localhost via TCP/IP
Server type: MariaDB
Server version: 10.1.14-MariaDB - mariadb.org binary distribution
Protocol version: 10
User: root@localhost
Server charset: UTF-8 Unicode (utf8)
Web server

Apache/2.4.17 (Win32) OpenSSL/1.0.2d PHP/5.6.20
Database client version: libmysql - mysqlnd 5.0.11-dev - 20120503 - $Id: 76b08b24596e12d4553bd41fc93cccd5bac2fe7a $
PHP extension: mysqliDocumentation curlDocumentation mbstringDocumentation
PHP version: 5.6.20
phpMyAdmin

Version information: 4.6.1 (up to date)
Documentation
Official Homepage
Contribute
Get support
List of changes
License

**Comment by nijel** [comment]
Okay, it seems that this happens in more cases when there is ``à<`` being rendered, so the workaround was definitely not good enough.

**Comment by nijel** [comment]
Okay, this is what seems to happen (though I still have no clue why does it happen):

The ``à`` character is stored as UTF-8 (``\xc3\xa0``) and the ``\xa0`` part is stripped. This seems to happen only when next char is ``<``. Also this happens only on Windows.

**Comment by nijel** [comment]
I've removed guilty code, so it should be fixed for good. The problem was that preg_replace doesn't properly handle utf-8 on Windows.

**Comment by vercinstex** [comment]
Hello
I've got same issue, but when I try to create a new table.

PhpMyAdmin 4.6.3
PHP version: 5.6.23 
Server version: 10.1.13-MariaDB 
Platform: Xampp on Win10

I do not receive any error in firebug console. :(
How can i help??

**Comment by nijel** [comment]
Please open separate issue for that, most likely it will be different issue.
