### ISSUE TITLE
Phpmyadmin SQL dump is not working properly in version 4.5.5.1

### ISSUE THREAD

**Issue by mikeross6233m** [phpmyadmin/phpmyadmin#12086]
### Steps to reproduce
1.Export any joomla or moodle (maybe even Wordpress database) from phpmyadmin 4.5.5.1(as I was testing on Joomla Site).
2.Now create a sample database and Import the sql file.
3.You will see error on import "#1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line joomla"

### Expected behaviour
The same database should be imported with no issue on the same phpmyadmin version.

### Actual behaviour
Phpmyadmin Sql dump is not producing .sql export file as of the previous versions. I checked the two sqldump files and there was a lot of differences in both files.

Gives error on database import.
### Server configuration

**Operating system**: Ubuntu 15.04

**Web server:Apache 2.4**

**Database: MySQL**

**PHP version:5.6.18-1**

**phpMyAdmin version:4.5.5.1**

### Client configuration
**Browser:Chrome**

**Operating system:Ubuntu 15.04**

**Comment by YoussefE123** [comment]
I noticed the same issue even with the latest version 4.6.0-rc2 before I switch to v4.5.5.1;
among the things that were omitted :

1. if there is a comment, you get something like
`'column' int(1) NOT NULL DEFAULT '0'COMMENT) `

2. **ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;**
is also removed from the end of the table creation;

also, there is an issue with quotes in the data :
`I'd like to ...` gets exported as `I\'d like to ...`
while in my latest sql dump, it was `I''d like to ...`
which even creates more errors when importing !

I tried to export to xml format, and it worked fine after importing (although the size is way bigger);
I don't know if it's just the sql format that has this issue;

Server configuration

Operating system : Windows 7 x64
Web server : Apache 2.4
Database: MariaDB 10.1.12
PHP version : 7.0.4

**Comment by madhuracj** [comment]
@YoussefE123 The issues highlighted in you comment have been reported in https://github.com/phpmyadmin/phpmyadmin/issues/12090 and https://github.com/phpmyadmin/phpmyadmin/issues/12054. They have been fixed targeting the upcoming 4.6.0 release.

@mikeross6233m It is possible that one of the two bugs (or both) are causing the issues for you. Can you attach a small export we can use to recreate the issue you experience?

**Comment by madhuracj** [comment]
Likely a duplicate of https://github.com/phpmyadmin/phpmyadmin/issues/12084

**Comment by foundationphp** [comment]
This is still a problem in 4.6.0-rc2. I exported a database from MariaDB 10.1.10 using 4.6.0.-rc2, renamed the original database, and used the dump file to import it. It choked on the first table (arrangements).

Dump file attached.
[hanselandpetal.sql.txt](https://github.com/phpmyadmin/phpmyadmin/files/171915/hanselandpetal.sql.txt)

**Comment by foundationphp** [comment]
Just done some further testing. Used mysqldump to export the same database on the command line, then tried importing using phpMyAdmin 4.6.0-rc2. The same error occurred.

One of the records contains the HTML character entity for an em dash (&mdash;). It looks as though phpMyAdmin is incorrectly interpreting the semicolon in the character entity as the end of an SQL statement. The dump files created both by phpMyAdmin and mysqldump load correctly when run from the command line.

Hope that helps identify the cause.

**Comment by ibennetch** [comment]
I've reduced your uploaded .sql.txt file to the following problematic SQL statement:

```
CREATE TABLE `arrangements` (
  `arrangement_id` tinyint(3) UNSIGNED NOT NULL,
  `description` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

INSERT INTO `arrangements` (`arrangement_id`, `description`) VALUES
(14, '<p>This is one for formal occasions, or to spoil someone who\'s really special. An exotic array of orchids in a deep red square vase.</p>\r\n<p>Donec non eros dui. Curabitur a dapibus enim. Nam fermentum, turpis ac laoreet rhoncus, arcu est accumsan est, a condimentum ligula nisl quis augue. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Fusce ut hendrerit tellus, ac aliquet arcu. Praesent volutpat, mauris vitae feugiat ullamcorper, quam neque tristique risus, rhoncus tempus tellus metus imperdiet tellus. Duis dolor diam, posuere fermentum est in, convallis condimentum nisl. Suspendisse a nisl vitae velit accumsan pretium sed at quam. Aliquam tincidunt in odio in scelerisque.</p>\r\n<p>Nulla faucibus, est a interdum volutpat, sem neque interdum dui, aliquam accumsan velit sapien nec purus. Integer quis massa vel odio viverra molestie. Duis rhoncus posuere felis. Proin lobortis feugiat dui, eget posuere mauris aliquet ut. Integer sagittis lacinia varius. Aenean sit amet nunc mauris. Aenean sed lobortis justo, non pharetra justo.</p>'),
(17, '<p>Carnations, daisies, and splashes of greenery&mdash;the perfect pick-me-up for someone feeling under the weather or just down in the dumps.</p>\r\n<p> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras pulvinar arcu pulvinar, dictum turpis vel, semper risus. Curabitur ac augue et felis tempor molestie. Fusce ligula libero, dignissim eget ultrices ut, varius sit amet massa. Curabitur luctus nulla non lacus malesuada, eget elementum arcu lacinia. Fusce et metus non nulla sodales hendrerit. Aenean vitae enim nunc. Integer ultrices erat ac nunc commodo, in mattis mi viverra. Nullam et vehicula orci.</p>\r\n<p>Sed accumsan, odio at vestibulum viverra, magna magna cursus mi, a venenatis nibh enim sagittis felis. Suspendisse elit tortor, dictum a est in, sollicitudin laoreet purus. Nullam quis porta tortor. Suspendisse potenti. Suspendisse commodo pulvinar arcu nec fringilla. Pellentesque dignissim scelerisque elit, nec sollicitudin turpis sodales ut. Sed eget elementum augue, non dapibus dui.</p>');
```

But I don't see anything obviously wrong here.

**Comment by foundationphp** [comment]
@ibennetch I've just tried loading your reduced version into the DB. The error is triggered, as noted in my second post, by the semicolon at the end of the HTML character entity &amp;mdash;. It seems as though phpMyAdmin is treating the semicolon as ending the query, so it's presumably complaining that there's no closing quote for the string. However, the semicolon is part of the string, not the end of the SQL statement.

**Comment by ibennetch** [comment]
I wasn't able to recreate the error when using the `&mdash;` entity by itself or in other queries I've tried; it only seems to happen when combined with the insert from id 14. It seems something about the `\'` followed by `;` is indeed the problem, but those statements all look correct so it's not obvious what the parse problem is. By the way, I've edited my demonstration case to cut out a few extra lines.

Do you always have trouble with inserting only `&mdash;` or is it only when used in your file as shown?

**Comment by foundationphp** [comment]
I've just tried exporting another database, and reimporting with equally bad results. I've cut down a much longer dumpfile to illustrate the problem.

This time, it's also choking on an HTML character entity (&amp;pound;).Notice, however, that the parse error is not triggered by the first instance of &amp;pound;. It happens only with id 2. Again, the issue appears to be the fact that there's an escaped quote in the description string before the semicolon in the character entity.

[gardendetails.sql.txt](https://github.com/phpmyadmin/phpmyadmin/files/172489/gardendetails.sql.txt)

**Comment by pigochu** [comment]
SOMETIMES IT WILL DUMP LIKE
~~~
COMMENT AS `ColumnName`
~~~

Can't import ><

if I change to
~~~
COMMENT 'ColumnName'
~~~

It works .

**Comment by TomaszKane** [comment]
Hi guys, could you consider add a test to this feature?

1. prepare "difficult" database with many "features"
2. do phpmyadmin export
3. check if console mysql correctly import previously dump

For now we have "stable" release with this (easy to find?) bug.

**Comment by pigochu** [comment]
![qq 20160321182451](https://cloud.githubusercontent.com/assets/1013744/13915886/3af4e8ce-ef92-11e5-99ed-39e76b056ae4.png)

export No error in console

![qq 20160321182721](https://cloud.githubusercontent.com/assets/1013744/13915946/98eec6ca-ef92-11e5-9099-b412cadf7e79.png)

import No error in console , but can't import

**Comment by ibennetch** [comment]
@pigochu Is this different from what was reported and fixed above?

**Comment by pigochu** [comment]
@ibennetch
my english is poor ^^ my error alson happed in 4.6.0-rc2
Should I open a new issue ?

**Comment by JorisDebonnet** [comment]
Both issues started at the same time, for me as well. Specifically: sometimes, the export will contain things like `NOT NULL DEFAULT '0'COMMENT)` (omitting all following fields), and sometimes, it will contain things like ``COMMENT AS `description of comment` `` (even with ). 

I do say "sometimes", because most comments are unharmed, and I honestly can't find any pattern to it. 

Both issues still occur in 4.6 RC2, but in the current master (as of commit 59a4878) the `'0'COMMENT)` one seems to be fixed. But the field where that happened now has ``'0' COMMENT AS `something` ``, so _that_ bug is still in master.

**Comment by JorisDebonnet** [comment]
The ``COMMENT AS `backtick` `` issue was introduced in version 4.5.5 (I verified that it's not there in 4.5.4). If the issue of _this bug_ was only introduced in 4.5.5.1, then I guess it is a different bug; just released very close together.

**Comment by YoussefE123** [comment]
Hi all,
I just installed the latest v4.6, and exporting then importing the same file;
the errors I mentioned seem to be fixed now;
Thanks

**Comment by TomaszKane** [comment]
My schema dump also works in 4.6.

**Comment by JorisDebonnet** [comment]
Strange, how did I miss that 4.6.0 was released when I wrote my previous posts... :/ my git pull must have failed or something. 

In any case, I can also verify that all issues are gone as of 4.6.0, so this can most likely be closed!

**Comment by pigochu** [comment]
4.6.0 works :+1:

**Comment by madhuracj** [comment]
Thanks for confirmations.

**Comment by hdfssk** [comment]
I’m sorry to say that @ibennatch ’s test case gives me an import error w/ both 4.6.0 & 4.6.1:

```
Error
Static analysis:

1 errors were found during analysis.

Ending quote ' was expected. (near "" at position 109)
SQL query:

INSERT INTO `arrangements` (`arrangement_id`, `description`) VALUES (14, '<p> who\'s</p>'), (17, '<p>&mdash

MySQL said: Documentation

#1064 - You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ''<p>&mdash' at line 3
```

**Environment**:

10.0.23-MariaDB - MariaDB Server
Apache/2.4.18 (Fedora) PHP/5.6.21
Database client version: libmysql - mysqlnd 5.0.11-dev - 20120503
phpMyAdmin version: 4.6.0 & 4.6.1

**Comment by YoussefE123** [comment]
Hi,
I think this issue is still not fixed yet, and I also noticed this error whenever the data contains a single quote; previously, single quote was exported as
`VALUES (14, '<p> who''s</p>')`
but in the last versions, it keeps escaping single quotes as
`VALUES (14, '<p> who\'s</p>')`

**Comment by jasaldivara** [comment]
I have the same issue that @JorisDebonnet says:

> Both issues started at the same time, for me as well. Specifically: sometimes, the export will contain things like NOT NULL DEFAULT '0'COMMENT) (omitting all following fields)

I'm on PhpmyAdmin 4.6.0, on Fedora 23

`Apache/2.4.18 (Fedora) OpenSSL/1.0.2h-fips PHP/5.6.21 mod_perl/2.0.9 Perl/v5.22.1
Versión del cliente de base de datos: libmysql - mysqlnd 5.0.11-dev - 20120503 - $Id: 76b08b24596e12d4553bd41fc93cccd5bac2fe7a $
extensión PHP: mysqliDocumentación curlDocumentación mbstringDocumentación
Versión de PHP: 5.6.21`

**Comment by pixelorigine** [comment]
Hi,
Same issue for me (antislash on sql export) with phpMyAdmin 4.5.5.1 (default version on WampServer 3.0.4) and the last phpMyAdmin 4.6.1.
**I fixed it by using phpMyAdmin 4.4.15.5** (https://www.phpmyadmin.net/downloads) on my WampServer 3.0.4 (Apache 2.4.18 / MySQL 5.7.11 / php 5.6.19). 
You can try phpMyAdmin 4.5.0.1, it's works too.

**Comment by washek** [comment]
Hi, we are experiencing the same issue in latest pMA (4.6.1). When exporting table with comment, the output is wrong and truncated (last field is missing).

Tha same issue was in 4.5.0.2. Operating system: Fedora 23 (pMA installed from official Fedora packages), PHP 5.6.21, Apache 2.4.18.

Preview of table structure:
![pma_comment](https://cloud.githubusercontent.com/assets/19268476/15534977/b169bfb4-226b-11e6-869e-a4d500a5e38c.png)

Export output:

```
  `header_text` mediumtext,
  `skryt_pro_preklad` int(1) NOT NULL DEFAULT '0'COMMENT
) ;
```

**Comment by jameswadsworth** [comment]
Fedora 23. php 5.6.23, apache 2.4.23 mariaDB 10.0.23

This is still happening in version 4.6.2 when the default value is set to 0 the export is truncated after the COMMENT column statement just as washek states

Example export output

CREATE TABLE `ia86w_modules` (
  `id` int(11) NOT NULL,
  `asset_id` int(10) UNSIGNED NOT NULL DEFAULT '0'COMMENT
) ;

**Comment by aenchevich** [comment]
phpMyAdmin 5.6.3 (in Fedora 22)  - still happening. In my case it happens with a drupal 7 database export.
