### ISSUE TITLE
Import file does not working when data have \' (4.6.0rc2)

### ISSUE THREAD

**Issue by 2002demon** [phpmyadmin/phpmyadmin#12091]
### Steps to reproduce
1. insert data like: 
**INSERT INTO `table` (`user`) VALUES ('data\'data');**
2. export table
3. import table => Error in SQL syntax
Also, import correct sql files with quoted apostrophe (\') is not possible.
Please fix this.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Server configuration
**Operating system**:

**Web server:**

**Database:**
MySQL 5.5
**PHP version:**
PHP 7
**phpMyAdmin version:**
4.6.0rc2
### Client configuration
**Browser:**

**Operating system:**

**Comment by ibennetch** [comment]
I'm not able to reproduce this. For instance, this is a portion of my export file that also imports correctly:

```
INSERT INTO `importquote` (`id`, `datum`) VALUES
(1, 'with\'quotes'),
(2, 'with\\\'escaped quotes');
```

Can you post here a small export showing your data?

**Comment by 2002demon** [comment]
Ok, i experimented now and to reproduce this bug, you need any sql line after INSERT, see at the bottom.
I think there was fixed here, but is not in rc2 included:
https://github.com/phpmyadmin/phpmyadmin/commit/fe4a3e8727164ceded739387c16f49bd2987431c

To reproduce copy in a file and import this:
`DROP TABLE IF EXISTS `ftps`;
CREATE TABLE `ftps` (
  `user` varchar(10) NOT NULL,
  `ftpuser` varchar(20) NOT NULL,
  `ftppass` varchar(34) NOT NULL,
  `path` varchar(255) NOT NULL,
  `anonymous` tinyint(1) NOT NULL,
  `count` int(10) NOT NULL,
  `traffic` bigint(14) NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

INSERT INTO `ftps` (`user`, `ftpuser`, `ftppass`, `path`, `anonymous`, `count`, `traffic`) VALUES
('test\'test', '', '', '', 0, 0, 0);

ALTER TABLE `ftps`
  ADD KEY `user` (`user`);
`

**Comment by madhuracj** [comment]
Duplicate of https://github.com/phpmyadmin/phpmyadmin/issues/12054

**Comment by yellow1912** [comment]
I still see this issue on the latest dev-master, is this changed already merged to the dev master?

**Comment by ibennetch** [comment]
Yes, @yellow1912  this should be fixed now.

If you're running the git master branch, you have to update the libraries (in this case, the SQL parser library) through Composer. `composer update` should take care of that.
