### ISSUE TITLE
SQL parser indicates error for Event definitions using BEGIN..END

### ISSUE THREAD

**Issue by grmblgrmbl** [phpmyadmin/phpmyadmin#12228]
### Steps to reproduce
1. Define an Event that has multiple statements, using BEGIN at the beginning and END in the end.
2. Open Event definition in phpmyadmin
3. Error is indicated for the END statement

### Example
`CREATE DEFINER=root@localhost EVENT Purge_logs ON SCHEDULE EVERY 30 MINUTE STARTS '2015-07-11 10:05:50' ON COMPLETION PRESERVE ENABLE COMMENT 'Purge old logs' DO BEGIN
DELETE FROM nk_log WHERE logtime < date_sub(NOW(), INTERVAL 10 DAY);
OPTIMIZE TABLE nk_log;
END`

### Expected behaviour
No error should be indicated.

### Server configuration
**Operating system**: Linux

**Web server:** Apache 2

**Database:** MySQL 5.5.47

**PHP version:** 5.6.20

**phpMyAdmin version:** 4.6.1

### Client configuration
**Browser:** Firefox 46

**Operating system:** Windows 10

**Comment by ibennetch** [comment]
Do you happen to know if this worked with previous versions?

**Comment by grmblgrmbl** [comment]
The problem was already in 4.6.0, but it worked in some earlier version (don't remember exactly which one, probably before 4.5.3).

**Comment by bobhairgrove** [comment]
It appears that the routine editor in phpMyAdmin flags almost every line of any stored procedure as an error -- I am using phpMyAdmin 4.5.4.1 with MySQL 5.7.13 on Linux Ubuntu 16.04 LTS. When I click on a stored procedure in the left panel, the "Edit routine" window opens like this (see attached screenshot).

Perhaps it is because it is parsing the code with delimiter ";"? There is apparently no option to set it anywhere.
![routine_editor_phpmyadmin_4 5 4 13](https://cloud.githubusercontent.com/assets/10685967/17291153/7ce3c4ae-57e2-11e6-9fc8-ac15ea5e079c.jpg)

**Comment by ibennetch** [comment]
@bobhairgrove I believe most (hopefully all!) of the problems you're seeing have been fixed for 4.6.x; the current version is 4.6.3 but I expect 4.6.4 to be released in the next week or two.

I suggest upgrading to take advantage of the fixes to the parser library.

**Comment by bobhairgrove** [comment]
Thank you! I have updated to 4.6.3 in the meantime. Most of the errors have gone away, but there is still a problem in a stored procedure when a label is encountered (see screenshot below):

![phpmyadmin_4 6 3_edit_routine](https://cloud.githubusercontent.com/assets/10685967/17319825/b16cc8c0-5890-11e6-86d4-ffff7b1ee97e.jpg)

**Comment by devenbansod** [comment]
If all the errors except the label error are fixed, then it is same as https://github.com/phpmyadmin/sql-parser/issues/57
