### ISSUE TITLE
View definitions not exported

### ISSUE THREAD

**Issue by divinoro** [phpmyadmin/phpmyadmin#12298]
### Steps to reproduce
1. choose DB with some views
2. select export, pick just structure
3. export to SQL

### Expected behaviour
View definitions should be exported

### Actual behaviour
Views are exported only as tables, but view definitions are missing

### Server configuration
**Operating system**:
Debian 8

**Web server:**
Apache 2.4.10

**Database:**
Mariadb 10

**PHP version:**
7.0.7

**phpMyAdmin version:**
4.6.2

### Client configuration
**Browser:**
Latest Firefox

**Operating system:**
Fedora Linux 23

Thank you.

**Comment by ZeNerzhul** [comment]
Same trouble,

Environnement : dev
OS : Windows 10
PHP : 5.6.12
Apache : 2.4.9
DB : MariaDb 10
PhpMyAdmin : 4.6.2

**Comment by divinoro** [comment]
Just realized, that Scheduled tasks are also not exported.

**Comment by monojp** [comment]
I have not tested every version going back, but for people that need the "CREATE ALGORITHM" statements for views: It works with version 4.5.5.1

**Comment by monojp** [comment]
I tested again with 4.6.2 and 4.6.3 with export-diffs and this issue has been fixed by d7fcbab1cda7432a78ec5f02ebb362bdfbdf677c. It is working now in 4.6.3!

**Comment by bobhairgrove** [comment]
This is still not working correctly on phpmyadmin 4.6.3 -- Linux 16.04 Ubuntu with Apache 2.4.18 / MySQL 5.7.13 / PHP 7.0.8.

First of all, the CREATE VIEW statement inserts extra space between the user and the "@" character:

![phpmyadmin_view_definition](https://cloud.githubusercontent.com/assets/10685967/17321816/c5a33f54-589a-11e6-91bf-97a83e45b917.jpg)

Secondly, I receive a lengthy notice about "Trying to get property of non-object", although the above (faulty) view definition is generated:

```
Notice in ./libraries/sql-parser/src/Components/Expression.php#419
Trying to get property of non-object

Backtrace

./libraries/sql-parser/src/Statements/CreateStatement.php#338: SqlParser\Components\Expression::build(NULL)
./libraries/plugins/export/ExportSql.php#2808: SqlParser\Statements\CreateStatement->build()
./libraries/plugins/export/ExportSql.php#1516: PMA\libraries\plugins\export\ExportSql->replaceWithAliases(
string 'CREATE ALGORITHM=UNDEFINED DEFINER=musik@localhost SQL SECURITY DEFINER VIEW iuImport.view_iu_new_all AS select distinct F.id AS id,F.nachname AS nachname,F.vorname AS vorname,F.abteilung AS abteilung,((case when (F.kurs_name like \'GI%\') then \'GF\' when (F.kurs_name like \'FI%\') then \'FF\' when (F.kurs_name like \'EI%\') then \'EF\' when (F.kurs_name like \'SI%\') then \'SF\' else \'KA\' end) collate utf8_unicode_ci) AS modus,(case when (F.kurs_name like \'GI%\') then 1 when (F.kurs_name like \'SI%\') then 2 when (F.kurs_name like \'EI%\') then 3 when (F.kurs_name like \'FI%\') then 4 else 5 end) AS sort_order,I.instr_id AS haupt_instr from (iuImport.import_faecherliste_DEF F join dbmusik.Instrumente I on((upper(substr(F.kurs_name,3,3)) = I.ins_kuerzel))) where ((length(F.kurs_name) = 5) and (upper(substr(F.kurs_name,1,2)) in (\'FI\',\'GI\',\'EI\',\'SI\'))) order by F.id,(case when (F.kurs_name like \'GI%\') then 1 when (F.kurs_name like \'SI%\') then 2 when (F.kurs_name like \'EI%\') then 3 when (F.kurs_name like \'FI%\') then 4 else 5 end)',
array,
string 'iuImport',
string 'view_iu_new_all',
boolean false,
)
./libraries/plugins/export/ExportSql.php#2076: PMA\libraries\plugins\export\ExportSql->getTableDef(
string 'iuImport',
string 'view_iu_new_all',
string ' ',
string 'db_export.php?db=iuImport&amp;token=e00ab8619fef29ce90128935eab1cacc',
boolean false,
boolean true,
boolean true,
boolean true,
array,
)
./libraries/export.lib.php#728: PMA\libraries\plugins\export\ExportSql->exportStructure(
string 'iuImport',
string 'view_iu_new_all',
string ' ',
string 'db_export.php?db=iuImport&amp;token=e00ab8619fef29ce90128935eab1cacc',
string 'create_view',
string 'database',
boolean false,
boolean true,
boolean false,
boolean false,
array,
)
./export.php#459: PMA_exportDatabase(
string 'iuImport',
array,
string 'structure_and_data',
array,
array,
,
string ' ',
string 'db_export.php?db=iuImport&amp;token=e00ab8619fef29ce90128935eab1cacc',
string 'database',
boolean false,
boolean true,
boolean false,
boolean false,
array,
string '',
)
```

**Comment by bobhairgrove** [comment]
Just checked, and the bug with the extra space between user and host occurs only when exported with the custom SQL option "Enclose table and column names with backquotes" unchecked. If it is checked, the user and host are quoted, and there is no extra space.
