### ISSUE TITLE
Wrong table status size reported

### ISSUE THREAD

**Issue by nijel** [phpmyadmin/phpmyadmin#12303]
Hi, over at Stack Overflow a user has a strange table size reported
(2.1,000,000,000,000,000,888 KiB; after running REPAIR one other table's
similar problem was fixed). This seems odd, our rounding of this number
should not produce such a strange number. Has anyone seen anything
similar to this? One table affected for one user doesn't make a very
good bug report, but if there's a shortcoming we of course want to try
to fix it. Any thoughts?

See http://stackoverflow.com/questions/37039116/weird-table-size-in-phpmyadmin-database-overview

**Comment by nijel** [comment]
To me it really looks like rounding issue. It should have printed "2.1 KiB".

The problem might be that we're using double for doing all the calculation. This can handle arbitrary numbers, but can produce arbitrary weirdness in the calculation as well.

The calculation in doubles was introduced in 1c4df63fe5103d661f6f6846566bec972681b322, but I'm not sure whether it is still necessary (now when basically everything is 64-bit and most likely anything where you will run database bigger than 2 GiB).

**Comment by AlBundyLoves69** [comment]
Hi Nijel, I found the problem: http://stackoverflow.com/a/37813148/3179492

**Comment by nijel** [comment]
Thanks for clarification, but anyway this should be fixed for next release as we will count using integers...

**Comment by AlBundyLoves69** [comment]
I am very sorry but this problem has NOT been fixed. It still persist when in php.ini the entry for precision > 16.

**Comment by nijel** [comment]
Have you tried that with 4.6.3? It no longer does this calculation in doubles.

**Comment by AlBundyLoves69** [comment]
Yes Nijel, of course. Once notified by phpMyAdmin that a new version is available I checked the change log where I saw the bug should have been fixed and I downloaded and installed it. Regrettably the bug is still there. Now it is even _worse_: Before there was a work around with the `php.ini` setting `precision` but now some tables display the wrong size regardless the value set in `precision`. I can offer you a TeamViewer session.

**Comment by nijel** [comment]
It should be fine in this particular case (4.6.2 -> 4.6.3 upgrade). Anyway I definitely need to look again at this.

**Comment by AlBundyLoves69** [comment]
I am so unbelievable sorry but the problem is still NOT fixed! When changing the php.ini setting precision = 19 then the table size is still displayed very weird.

![2016-08-30_15-00-47](https://cloud.githubusercontent.com/assets/9625486/18089957/af7e8452-6ec2-11e6-810b-8966ae15e5ef.png)

**Comment by nijel** [comment]
Hmm, there seems to be some implicit conversion to float somewhere. I'll look again.

**Comment by nijel** [comment]
Hmm, when playing with it, you can really expect lot of weird things from PHP when changing precision. Let's take simple script:

```php
<?php echo round(1.2, 2); ?>
```

With default precision=14 it returns what you would expect:

```
1.2
```

However with precision=19 things go weird:

```
1.199999999999999956
```

Our code was simply built around some sane expectations on the language and they don't seem to be working in this case.

**Comment by AlBundyLoves69** [comment]
Now I understand exactly the wrong output. Report it to PHP as bug?

**Comment by nijel** [comment]
It's probably desired behavior (see eg. https://www.leaseweb.com/labs/2013/06/the-php-floating-point-precision-is-wrong-by-default/). There was also bug in our code which made this more visible, which I've fixed in f3ca367.
