### ISSUE TITLE
Edit/Export links are not clickable under Routines tab

### ISSUE THREAD

**Issue by silverasu** [phpmyadmin/phpmyadmin#12769]
### Steps to reproduce
1. Create any routine (Procedure)
2. Click Routines
3. Only Drop link is working. Edit and Export does not work

### Expected behaviour
Edit and Export links should work as User has all privileges to Database.

### Actual behaviour
Edit and Export are not clickable

### Server configuration
**Operating system**:
Centos5

**Web server:**
Apache 2.4

**Database:**
MySQL 5.6

**PHP version:**
7.0

**phpMyAdmin version:**
4.6.5.1 (4.6.4 is OK)

### Client configuration
**Browser:**
Chrome

**Operating system:**
Windows 10

**Comment by nijel** [comment]
Most likely this is caused f8ea67f2bc59d46290b85b2e578c649655f000e7 which is fix for #12530.

**Comment by silverasu** [comment]
Our information_schema.TABLE_PRIVILEGES is empty. This is probably because users are added without GRANT, directly to mysql.* tables?
"SHOW GRANTS" shows ALL PRIVILEGES tho...

**Comment by silverasu** [comment]
There is problem with $routine_definer too. If you select it over controllink this shows nothing. It should be changed to user connection. 
$routine_definer = $GLOBALS['dbi']->fetchValue($query);

**Comment by nijel** [comment]
Fixed by https://github.com/phpmyadmin/phpmyadmin/pull/12770

**Comment by silverasu** [comment]
For us, this does not fix the problem. This worked:

--- phpMyAdmin-4.6.5.1-all-languages/libraries/rte/rte_list.lib.php     2016-11-26 06:41:54.000000000 +0200
+++ phpMyAdmin/libraries/rte/rte_list.lib.php   2016-12-02 11:12:55.334207668 +0200
@@ -204,9 +204,9 @@
         . "AND SPECIFIC_NAME='" . $GLOBALS['dbi']->escapeString($routine['name']) . "'"
         . "AND ROUTINE_TYPE='" . $GLOBALS['dbi']->escapeString($routine['type']) . "'";
     $query = "SELECT `DEFINER` FROM INFORMATION_SCHEMA.ROUTINES WHERE $where;";
-    $routine_definer = $GLOBALS['dbi']->fetchValue($query, 0, 0, $GLOBALS['controllink']);
+    $routine_definer = $GLOBALS['dbi']->fetchValue($query);
 
-    $curr_user = $GLOBALS['dbi']->getCurrentUser();
+    $curr_user = $GLOBALS['dbi']->fetchValue('SELECT CURRENT_USER()');

**Comment by devenbansod** [comment]
I believe it does makes sense. 
Since `INFORMATION_SCHEMA` would have the required information populated that the user can query (given his/her permissions), we can use `$GLOBALS['userlink']` instead of `$GLOBALS['controllink']`. 

Changed in https://github.com/phpmyadmin/phpmyadmin/commit/82c369334d6def8262d7fa6a0aa799143e88b044
