### ISSUE TITLE
Central columns don't set some properties

### ISSUE THREAD

**Issue by stevenwdv** [phpmyadmin/phpmyadmin#13176]
### Steps to reproduce
1. Add an `UNSIGNED` and/or `AUTO_INCREMENT` column to central columns
2. Create a new table and click _Pick from central columns_
3. _Attributes_ and _A_I_ remain unchanged (although the values *are* set when viewing central columns)

The same happens with the `Null` collumn: it is not changed.
Attributes other than `UNSIGNED` have the same problems as `UNSIGNED`.

### Expected behaviour
_Attributes_ should be set to `UNSIGNED` and/or _A_I_ should be activated

### Actual behaviour
Both values remain unchanged

### Server configuration
**Operating system**: Windows 10 x64

**Web server:** Apache 2.4.25 x86

**Database:** MariaDB 10.2.5 RC x64

**PHP version:** 7.1.1 x86

**phpMyAdmin version:** 4.7.0

### Client configuration
**Browser:** Microsoft Edge 14, Mozilla Firefox 52.0.2

**Operating system:** Windows 10 x64

**Comment by aswaniprakash** [comment]
Hi @stevenwdv, 

Similar issue fixed by [1709918](https://github.com/phpmyadmin/phpmyadmin/commit/17099186beebbaaf57ca385911484bcf3f506440)

**Comment by williamdes** [comment]
Hi @stevenwdv, years have passed and in my latest test I could not reproduce the behavior
Can you confirm it is not solved or close the issue?

_I will auto close this issue if no answer is given in some time since the issue is quite old_
