### ISSUE TITLE
Grid editing repeats action after error

### ISSUE THREAD

**Issue by stevenwdv** [phpmyadmin/phpmyadmin#13177]
### Steps to reproduce
1. Create a new table
2. Go to _Browse_
3. Double-click a cell to edit it
4. Enter an illegal value (e.g. too long) and proceed
5. PHPMyAdmin will promt you with an error
6. Click on the error
7. The box will go away but almost immediately return

### Expected behaviour
PHPMyAdmin should cancel the editing action after the error popup is clicked

### Actual behaviour
It tries to change the value again, prompting with the same error afterwards

### Server configuration
**Operating system**: Windows 10 x64

**Web server:** Apache 2.4.25 x86

**Database:** MariaDB 10.2.5 RC x64

**PHP version:** 7.1.1 x86

**phpMyAdmin version:** 4.7.0

### Client configuration
**Browser:** Microsoft Edge 14, Mozilla Firefox 52.0.2

**Operating system:** Windows 10 x64

**Comment by jajodiaraghav** [comment]
Can this be fixed by someone new to the codebase. Where should one look at to fix this?

**Comment by stevenwdv** [comment]
Unfortunately the issue is still present in v4.7.3

**Comment by stevenwdv** [comment]
@madhuracj I can confirm this still happens in PMA v4.7.4. Again, could this be reopened?

**Comment by madhuracj** [comment]
The fix simply avoids a second save call when the user clicks on the error popup to dismiss it, which caused the endless loop of errors. It does not cancel the editing allowing the user to enter a different value if appropriate to the error. The user can cancel editing using the escape key.

**Comment by stevenwdv** [comment]
@madhuracj The fix does not always work, though, as demonstrated in this video: 
[pma grid edit repeat.zip](https://github.com/phpmyadmin/phpmyadmin/files/1260142/pma.grid.edit.repeat.zip)

**Comment by madhuracj** [comment]
Thanks for the video. Can you test the patch https://github.com/phpmyadmin/phpmyadmin/commit/f4d77f905df82746052a9e749e4aa040bb202d4f please.

**Comment by stevenwdv** [comment]
@madhuracj It seems to work, thanks!
