### ISSUE TITLE
count() function error on PHP7.2

### ISSUE THREAD

**Issue by Om3rCitak** [phpmyadmin/phpmyadmin#13932]
### Steps to reproduce
1. Install phpmyadmin 4.5.4.1deb2ubuntu2 on php 7.2
2. Create db
3. Create table and columns
4. Add rows at the table
5. Click table name on the left sidebar (browse table)

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Server configuration
**Operating system**: Ubuntu 16.04.3

**Web server:** Apache 2.4.18

**Database:** MySQL 5.7.20-0ubuntu0.16.04.1

**PHP version:**  7.2.1-1+ubuntu16.04.1+deb.sury.org+1

**phpMyAdmin version:** 4.5.4.1deb2ubuntu2

### Client configuration
**Browser:** Chrome Latest

**Operating system:** Ubuntu 16.04.3

### Details
PhpMyAdmin printing this error:
```
Warning in ./libraries/sql.lib.php#601
 count(): Parameter must be an array or an object that implements Countable

Backtrace

./libraries/sql.lib.php#2038: PMA_isRememberSortingOrder(array)
./libraries/sql.lib.php#1984: PMA_executeQueryAndGetQueryResponse(
array,
boolean true,
string '3hanedan',
string 'map_data',
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
string '',
string './themes/pmahomme/img/',
NULL,
NULL,
NULL,
string 'SELECT * FROM `map_data`',
NULL,
NULL,
)
./sql.php#216: PMA_executeQueryAndSendQueryResponse(
array,
boolean true,
string '3hanedan',
string 'map_data',
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
string '',
string './themes/pmahomme/img/',
NULL,
NULL,
NULL,
string 'SELECT * FROM `map_data`',
NULL,
NULL,
)
```

**Comment by mauriciofauth** [comment]
Related to #13938

**Comment by mauriciofauth** [comment]
Thank you for reporting. This was fixed in 4ef752e.

**Comment by gtw1986** [comment]
I'm still having the exact problem even with the latest version release.

**Comment by ibennetch** [comment]
@gtw1986 Could you please confirm which phpMyAdmin version you're using? You can see the version information on the main page when you first load phpMyAdmin, on the right side under the heading "phpMyAdmin".

**Comment by pratiksnaik** [comment]
Ubuntu 16.04
phpMyAdmin Version: Version information: 4.6.6deb1+deb.cihar.com~xenial.2
Still facing the same issue.

**Comment by johnfrancisgit** [comment]
+1 via apt-get

**Comment by sulyokg** [comment]
Same problem with: Ubuntu server 18.04 + phpMyAdmin 4.6.6deb5 + php 7.2.5-0ubuntu0.18.04.1 + mysql 5.7.22-0ubuntu18.04.1
phpMyAdmin is installed via apt (no updates available at this time)

**Comment by kolorete78** [comment]
Same problem with Ubuntu 18.04 + PHP 7.2.5-0ubuntu0.18.04.1 + Apache/2.4.29 (Ubuntu) + Mysql 5.7.22-0ubuntu18.04.1 - (Ubuntu) + PHPMyadmin 4.6.6deb5

No updates availables at this moment.

**Comment by ibennetch** [comment]
Unfortunately, we don't directly control the Debian and Ubuntu packages. You should ask through the appropriate means for those distributions about an update — or you can remove the packaged version and [install your own](https://docs.phpmyadmin.net/en/latest/setup.html#quick-install).
