### ISSUE TITLE
SQL tab already has a query loaded

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/phpmyadmin#14118]
With my current master, going to any SQL tab I see some previous query filled in already in the query area. For me, it seems to be:

```
SHOW VARIABLES WHERE Variable_name LIKE  'character\_set\_%' OR Variable_name LIKE  'collation%'
```
 but it may vary depending on what SQL was most recently executed.

**Comment by shucon** [comment]
It was a mistake from my side. Gets fixed in https://github.com/phpmyadmin/phpmyadmin/pull/14094

**Comment by ibennetch** [comment]
Even with that pull request, I still have some old queries stuck in my SQL window.

**Comment by shucon** [comment]
I'm aware of that, there many different cases where localstorage has to
handled. I'm thinking what's the best way possible.

**Comment by ibennetch** [comment]
Okay, no worries.
