### ISSUE TITLE
Theme problem in 4.8 version

### ISSUE THREAD

**Issue by wcizmowski** [phpmyadmin/phpmyadmin#14175]
### Steps to reproduce
1. clone phpMyAdmin
2. copy metro theme into thees folder
3. theme do not work....

### Expected behaviour
Tell us what should happen
Metro style should be visible

### Actual behaviour
Tell us what happens instead
Nothing happend after change into metro style

### Server configuration
**Operating system**:
Linux Mint (latest with updates)

**Web server:**
nginx from docker

**Database:**
MariaDB 10.1

**PHP version:**
7.1

**phpMyAdmin version:**
4.8

### Client configuration
**Browser:**
Chrome latest

**Operating system:**
Linux Mint

**Comment by nulll-pointer** [comment]
The supports parameter in the theme.json file says '4.7', changing it to 4.9 shows the theme in the themes options, but the theme doesn't work, I think you should wait for a new release of this theme.

**Comment by nulll-pointer** [comment]
It would be very difficult for other people to make it compatible with new versions, probably you'll have to wait for a new release.

**Comment by ayurmedia** [comment]
themes are broken "metro 4.7" is impossible to use. even if you create theme.json 100 broken links

**Comment by mauriciofauth** [comment]
The Metro theme is now working on the [demo](https://demo.phpmyadmin.net/QA_4_8/). We just need to make it available for download on the [website](https://www.phpmyadmin.net/themes/).

**Comment by ibennetch** [comment]
There are a lot of layers to this report.

First, you've called my attention to the fact that our web page at https://www.phpmyadmin.net/themes/ doesn't list any 4.8 themes, even though metro is compatible with version 4.8.

Editing the theme.json file won't accomplish much because the rest of the theme still isn't updated.

@wcizmowski From where did you get the metro theme? You can download it from the theme repository at https://github.com/phpmyadmin/themes which will give you a version compatible with 4.8. We'll continue to investigate why metro isn't showing at phpmyadmin.net as compatible with 4.8, if I had to guess I'd say it's probably a version tag issue.

Themes are generally submitted and maintained by third party contributors so they're often not updated quickly after a release (or ever, in many cases). Pull requests against the theme repository are welcome. The themes that are officially maintained and distributed as part of the phpMyAdmin download are kept up to date with the current version.

**Comment by ibennetch** [comment]
I've just published Maurício's work on Metro at https://www.phpmyadmin.net/themes/#pma_4_8

**Comment by joho1968** [comment]
I just upgraded a phpMyAdmin instance to 4.8.0.1 and the metro theme to the one in the above link, still not working. I previously had Metro theme working nicely with phpMyAdmin. This is a completely fresh phpMyAdmin installation, I only moved the config from the previous installation. Even if I enable the Theme Manager and select Metro, nothing happens. I'm sure it's my fault somehow, but just in case I did it right, I'm reporting it here.
