### ISSUE TITLE
Failed to set session cookie. Maybe you are using HTTP instead of HTTPS

### ISSUE THREAD

**Issue by nik6018** [phpmyadmin/phpmyadmin#14184]
### Steps to reproduce
1. Install PMA 4.8.0
2. Login via HTTP

### Expected behaviour
After entering the login information, I should be able to log in

### Actual behaviour
It doen't log me in and fails with this error : **Failed to set session cookie. Maybe you are using HTTP instead of HTTPS** 
In previous version of PMA 4.7.9 I didn't face this issue I was able to log in via HTTP and HTTPS without any issue.
Now I am only able to login via HTTPS.

How can I disable this as I cannot find anything in the docs, the closest thing I was able to find is this [Link](https://docs.phpmyadmin.net/en/latest/setup.html?#http-authentication-mode)

I am really confused about this.

I checked the file `common.inc.php` where this error is mentioned, but still wasn't able to figure out the issue.

### Web Server configuration

      server{

		listen	   2002;
		listen	   2004;
		server_name  localhost;
		
		# The Document Root
		root	/custom/path;
		
		rewrite "/sess([0-9a-zA-Z]{16})/(.*)" /$2;
		
		# Redirect server error pages to the static pages
		error_page  404					/nginx/404.html;
		error_page  497					/nginx/497.html;
		error_page  500 502 503 504		/nginx/50x.html;		
		location ~ (index.php|/)$ {
		
			fastcgi_pass	unix:/usr/local/php/var/fpm9178.sock;
			if ($uri ~ "^/phpmyadmin/") {
				fastcgi_pass	unix:/usr/local/php/var/fpm9179.sock;
			}
			fastcgi_read_timeout 3600;
			fastcgi_index	index.php;
			fastcgi_param	SCRIPT_FILENAME  $document_root$fastcgi_script_name;
			fastcgi_param	SCRIPT_NAME	  $fastcgi_script_name;
			include			fastcgi_params;
		}
	
		location ~ \.php$ {
			fastcgi_pass	unix:/usr/local/php/var/fpm9178.sock;
			if ($uri ~ "^/phpmyadmin/") {
				fastcgi_pass	unix:/usr/local/php/var/fpm9179.sock;
			}

			fastcgi_read_timeout 3600;
			fastcgi_index	index.php;
			fastcgi_param	SCRIPT_FILENAME	$document_root$fastcgi_script_name;
			fastcgi_param	SCRIPT_NAME		$fastcgi_script_name;
			include			fastcgi_params;
		}
		
		client_max_body_size 50M;
	}

### Server configuration
**Operating system**:
CentOS and Ubuntu 

**Web server:**
Nginx 1.12.2

**Database:**
MySQL 5.5.59

**PHP version:**
PHP 5.6.35

**phpMyAdmin version:**
4.8.0

### Client configuration
**Browser:**
Chrome, FireFox

**Operating system:**
Windows

**Comment by ibennetch** [comment]
When you see the error, can you try logging in again? This workaround seems to function for me until we get this fixed.

**Comment by nik6018** [comment]
@ibennetch  yes I tried this multiple times it doesn't work for me.

**Comment by ibennetch** [comment]
See also https://stackoverflow.com/q/49811804/2385479 for another person with this problem.

**Comment by williamdes** [comment]
I have this issue when my session has expired and I try to login.
What happens :
1. Try to login when session is expired
2. Fails with this message
3. Try again
4. Login OK

Screenshot :
![selection_019](https://user-images.githubusercontent.com/7784660/38781621-4a62372c-40e8-11e8-8f06-ef7f70644e0e.jpg)

**Comment by nik6018** [comment]
@ibennetch  In 4.8.0.1 I am only facing this in Chrome.  FireFox and Edge work fine.
It seems that during the initial request after entering the login details there is a 302 redirect which logs me in FireFox and Edge.
That redirect is not happening in Chrome
Can you give me a hint on how can I check and debug this?

**Comment by D-AIRY** [comment]
Same error in Firefox 59. In my case issue caused by javascript error which makes tracekit library to query server and rewrite cookies.
As a quick workaround: edit file ./js/vendor/tracekit.js - add return in start of function `traceKitWindowOnError`

**Comment by voltel** [comment]
I have the same issue. Run http://phpmyadmin/index.php, provide MySQL valid credentials, have the same error message ("Failed to set session cookie. Maybe you are using HTTP instead of HTTPS to access phpMyAdmin."). So, I checked both FireFox 59.0.2 (64-bit) and Chrome 66.0.3359.117 - the error is reproduced in either browser.

**Comment by fraban** [comment]
Hi - I discovered exactly the same error when switching to 4.8.0.1 from 4.7.9 .
Server is ubuntu 14.04 LTS with  nginx/1.10.1 and 5.5.59-MariaDB-1ubuntu0.14.04.1  
Testing with phpMyadmin 4.8.0.1 exactly the errors reported here. Going back to 4.7.9 everything is working again. I can reproduce with Firefox and Safari - Chrome not tested

**Comment by williamdes** [comment]
@fraban @voltel @ntinti You all seem to have the same issue.
 Can you send the request and response headers of a login request.

Eg (success) :
**General**
```
Request URL: http://localhost:2002/phpmyadmintest/index.php
Request Method: POST
Status Code: 302 Found
Remote Address: 127.0.0.1:2002
Referrer Policy: no-referrer
```
**Form data**
```
set_session: ss7v6rnrnp3s62qk7so1v9bphb
pma_username: root
pma_password: testbench
server: 1
target: index.php
token: %+22p!b+!=LlroZ+
```
**Response-Headers**
```
Cache-Control: private, max-age=10800
Connection: keep-alive
Content-Encoding: gzip
Content-Type: text/html; charset=utf-8
Date: Thu, 26 Apr 2018 16:24:49 GMT
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Last-Modified: Thu, 26 Apr 2018 15:53:21 GMT
Location: /phpmyadmintest/index.php
Server: nginx/1.14.0 (Ubuntu)
Set-Cookie: phpMyAdmin=icfqhbpq7hdpt1aktr34974tg4; path=/phpmyadmintest/; HttpOnly
Set-Cookie: pmaUser-1=%7B%22iv%22%3A%22CCvj06ZDKtfww0h9t%5C%2Fh2UQ%3D%3D%22%2C%22mac%22%3A%22c6c8ac86787ec25a6243072277d3074f38491018%22%2C%22payload%22%3A%220OCYLzRa3uL8csuSTA6FrQ%3D%3D%22%7D; expires=Sat, 26-May-2018 16:24:49 GMT; Max-Age=2592000; path=/phpmyadmintest/; HttpOnly
Set-Cookie: pmaAuth-1=%7B%22iv%22%3A%220QouYNeqzPuvVe8qfW7wig%3D%3D%22%2C%22mac%22%3A%228ab39fb5acbc364731ea10df1572a0e43ed64721%22%2C%22payload%22%3A%22nVar7gfH9nlkP2uGhVG6w%2BuJ9yW4H3UU%2BW2M0VfbDhA%3D%22%7D; path=/phpmyadmintest/; HttpOnly
Transfer-Encoding: chunked
Vary: Accept-Encoding
X-ob_mode: 1
```
**Request-Headers**
```
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
Accept-Encoding: gzip, deflate, br
Accept-Language: fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7
Cache-Control: no-cache
Connection: keep-alive
Content-Length: 142
Content-Type: application/x-www-form-urlencoded
Cookie: pma_lang=fr; pmaUser-1=%7B%22iv%22%3A%227eJ9nBG1lzpVqgsWzCb50w%3D%3D%22%2C%22mac%22%3A%22c6d37dd0aa1e4b128c7488500f7037386bdd5ce2%22%2C%22payload%22%3A%22VL%5C%2F3nPuADZlfIXNRuPMphQ%3D%3D%22%7D; phpMyAdmin=ss7v6rnrnp3s62qk7so1v9bphb
DNT: 1
Host: localhost:2002
Origin: null
Pragma: no-cache
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36
```

This check was introduced in https://github.com/phpmyadmin/phpmyadmin/commit/0a1634a12bbcdf3f7147b5fd44ae4fbcace53d57

**Comment by williamdes** [comment]
Thanks to @ntinti https://github.com/phpmyadmin/phpmyadmin/issues/14219#issuecomment-385626406 this is the reason for this error (`Call to a member function exists() on null`):
# Reproduce
```sql
-- Random IP
UPDATE mysql.db SET host='127.1.2.1' WHERE Db='phpmyadmin';
FLUSH PRIVILEGES;
-- Now phpmyadmin fails on login : HTTP ERROR 500

-- Assuming host was % before
UPDATE mysql.db SET host='%' WHERE Db='phpmyadmin';
FLUSH PRIVILEGES;
-- Now phpmyadmin succeeds on login
```
# Stacktrace
```
2018/05/01 17:25:33 [error] 4492#4492: *729 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to a member function exists() on null in /mnt/Dev/phpmyadmintest/libraries/classes/DatabaseInterface.php:1588
Stack trace:
#0 /mnt/Dev/phpmyadmintest/libraries/classes/DatabaseInterface.php(2544): PhpMyAdmin\DatabaseInterface->postConnectControl()
#1 /mnt/Dev/phpmyadmintest/libraries/common.inc.php(352): PhpMyAdmin\DatabaseInterface->connect(257)
#2 /mnt/Dev/phpmyadmintest/index.php(26): require_once('/mnt/Dev/phpmya...')
#3 {main}
  thrown in /mnt/Dev/phpmyadmintest/libraries/classes/DatabaseInterface.php on line 1588" while reading response header from upstream, client: 127.0.0.1, server: localhost.localdomain, request: "POST /phpmyadmintest/index.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.2-fpm.sock:", host: "localhost.localdomain"
```

@AlviseNicoletti @Hakeem-Olasupo @fraban @voltel Check your controluser

**Comment by AlviseNicoletti** [comment]
This solution is not working for me, however, **I want to clarify my situation**:

I have phpmyadmin 4.7.9 perfectly working,
when I upgrade to 4.8.1 (removing and then copying new files except config.php) I get this error.

**Comment by nik6018** [comment]
As stated in #14234  Login via HTTP works if in private mode, but doesn't work in normal session.
I tried to clear the cookie for the domain but still the same issue.

**Comment by COLABORATI** [comment]
Things like login are not tested with this software before a release? Interesting to know!

**Comment by nik6018** [comment]
@ibennetch Can you please update us with any planned fix for this?

**Comment by williamdes** [comment]
@ibennetch @mauriciofauth If I understand correctly, we use a session "token" to avoid CSRF attacks.
Correct me if that is not exact.
Can we use another way of validating the login form, that is not based on sessions ?
HMAC ?
Sessions expire :laughing: ...

To end the issue explained in https://github.com/phpmyadmin/phpmyadmin/issues/14184#issuecomment-381425826:
- Change `session_set_cookie_params` secure option to false
OR
- Use a different cookie name for secure session

Please give me feedback on this, I can work on a PR.

**Comment by williamdes** [comment]
delete cache in `tmp` ?
fresh install in same directory ?
Use my phpMyAdmin autoupdate script to try upgrading/reinstalling https://gist.github.com/williamdes/883f2158f17e9ed5a83d892ada56f5df

**Comment by gavtaylor** [comment]
Ive been getting this error since upgrading to 4.8.0 as well but I dont access via http, my install is https only.

the message is being triggered when trying to login after a session has expired, opening the login page in a private tab logs in first time. a standard tab errors on first attempt, logs in on the second.

**Comment by williamdes** [comment]
Seems to be 2/2, the token verification of the form.
If the error if after cookie expired this is "normal" in the context of this issue.

You have the same error with opening +login for the first time in private mode ?
What browser do you use ?

**Comment by gavtaylor** [comment]
no it logs in first time on private tabs, standard tabs login first time too if I log out and open a new tab. its just the expired session triggering this error for me. 

I just wanted to mention that my install is HTTPS only, everyone commenting so far has mentioned they also login via http.

I use Firefox (dev edition) but have tested in chrome (stable) as well in case it was a brwoser niggle.

**Comment by nuxwin** [comment]
When login the first time through HTTPS, a secure cookie is set... The problem is that if an user logout and then attempt to login again through HTTP, that will fails because there is already a secure cookie set that of course cannot be sent through HTTP. Same behavior occurs a session timeout when an user need login again. Basically, if a secure cookie is set, user will have to login through HTTPS only.

There are some browsers allowing setting secure cookies via HTTP protocole but that is a wrong behavior which has been recently deprecated (For instance: FF 52).

There are not reliable solution here. Once the secure cookie is set and if an user want login through HTTP, it will have to remove the secure cookie first. The annoying thing is that you cannot unset a secure cookie for a specific domain via HTTP protocol... The only solution I see here is to set specific session name for both HTTP and HTTPS but this could lead to side effect I think.

**Comment by dinodan** [comment]
1. Change file name "js/vendor/**js.cookie.js**" to "js/vendor/**jscookie.js**".
2. In file "**libraries/classes/Header.php**" change "$this->_scripts->addFile('vendor/**js.cookie.js**');" to "$this->_scripts->addFile('vendor/**jscookie.js**');"

**Comment by svivian** [comment]
I had the same issue, where PMA just wouldn't log in at all. Turns out it was uBlock Origin preventing the file `/js/vendor/js.cookie.js?v=4.8.2` from loading. After disabling the ad blocker everything works fine.

**Comment by DougTy** [comment]
Can confirm, for me it was uBlock Origin blocking `js/vendor/js.cookie.js?v=4.8.2`. Source seems to be Fanboy’s Cookiemonster List. Hitting "Purge All Caches" and "Update Now" in the "Filter Lists" settings page of uBlock seems to have fixed it for me without needing to disable the list entirely.

**Comment by cochrasc** [comment]
@Zangwill You've saved me from going bald.  I've been pulling my hair out for months trying to figure it out. For me, this issue also turned out to be because of the Katalon Recorder (Selenium IDE extension).

**Comment by williamdes** [comment]
Param | Value 
 -----------|--------------------
 Error Type | User Error
 Error Message |Failed to set session cookie. Maybe you are using HTTP instead of HTTPS to access phpMyAdmin.
 Exception Type |php
 phpMyAdmin version |4.8.4
 Incident count | 1
 Link | [Report#54621](https://reports.phpmyadmin.net/reports/view/54621)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by nPHYN1T3** [comment]
I have this issue as well in 4.8.4. Private tabs work, normal do not (in any browser).  My primary is Firefox 64.0.

This is obnoxious because not only am I constantly having to log back in but I will have to refresh the page before I login. So I will be idle too long, go to do something and it will kick me back to a login with the error. If I login, error. However if I refresh the page before trying to login it works.

**Comment by z0921** [comment]
I also have this problem in the normal mode of Google Chrome, but when I log in through the seamless browsing mode of Google Chrome, this problem no longer occurs, which may be caused by a conflict with one of my browser plugins.

**Comment by voltel** [comment]
Dear fellow php programmers,

May I share with you the solution I have found to this problem of ours. As I understand, there might be a multitude of reasons all of which are having the same misleading presentation – the infamous "_Failed to set session cookie. Maybe you are using HTTP instead of HTTPS_" error. So, I guess at least some of you could possibly have the same _problem root cause_ as I had, so the following solution may be of help. 
I work under Windows 10, use Firefox 65.0, PHP version 7.1.6,  Apache 2.4.26, MySQL 5.7.18, just to give you the context. 

After many experiments, I just happened to have PhpMyAdmin 'http' authentication work fine, under php development server, with url having 'http://' schema. Simply speaking,  I issued a command in the terminal (`d:\WebSites\phpmyadmin>php -S 127.0.0.1:80 `), changed in phpmyadmin configuration file ("config.inc.php") authentication type to 'http', issued in the browser address bar 'http://phpmyadmin/', got a login form and was able to authenticate into my MySQL account. 

But, when I was trying to do the same under Apache, this misleading error message about problem with setting cookies presented itself. So, I went to see the cookies that had been set under the development php server, and I found them under the Storage/Cookies tab of WebDeveloper Inspector. When I repeated this operation to see the cookies set under Apache server, I noticed the strangest thing: the *path* on the set cookies was not an expected "/" but a "/D:/". 

So, I dived into the phpmyadmin code to find the code setting the cookies, one thing led to the other, and I found in "libraries/config.default.php" file this configuration parameter – "PmaAbsoluteUri" – the first of the TON of them with the following description (excerpt): 
>  In most cases you can leave this variable empty, as the correct value
>  will be detected automatically. However, we recommend that you do
>  test to see that the auto-detection code works in your system. 

So, guess what, I set the parameter to `'http://phpmyadmin/'` along with other "usual configuration parameters: 
> $cfg['PmaAbsoluteUri'] = 'http://phpmyadmin/';
> $cfg['Servers'][$i]['auth_type'] = 'cookie';
> /* Server parameters */
> $cfg['Servers'][$i]['host'] = 'phpmyadmin';
> $cfg['Servers'][$i]['compress'] = false;
> $cfg['Servers'][$i]['AllowNoPassword'] = false;
 
Just to give more context, I had "phpmyadmin" domain name declared in my "C:\Windows\System32\drivers\etc\hosts": 
> `127.0.0.2 phpmyadmin pma`

And in "D:\Apache24\conf\extra\httpd-vhosts.conf" file the most usual: 

> \<VirtualHost phpmyadmin:80\>
>     DocumentRoot "${DOCROOT}/phpmyadmin"
>     ServerName phpmyadmin
>     ServerAlias pma
>     ErrorLog "logs/pma-error.log"
>     CustomLog "logs/pma-access.log" common
> 
> 	\<Directory "${DOCROOT}/phpmyadmin"\>
>  		Options Indexes FollowSymLinks
>  		AllowOverride Indexes
>  		Require all granted
>  		FallbackResource /index.php
>  	\</Directory\>
> \</VirtualHost\>



That's it. The 'cookie' authentication works under Apache too. Hooray! But...
The 'http' authentication stopped working; this needs more debugging but currently doesn't bother me much. 

I hope, the PhpMyAdmin developers will notice this post and react appropriately.

**Comment by marin1993** [comment]
在config.inc.php中设置$cfg['PmaAbsoluteUri'] = '';值为你在浏览器访问的phpmyadmin的url的路径，比如我通过nginx代理转发到私网的地址$cfg['PmaAbsoluteUri'] = 'https://192.168.1.10/db/';
nginx 配置为
server {
        listen       443 ssl http2;
        server_name  192.168.1.10;

        ssl_certificate      server.pem;
        ssl_certificate_key  server.key;

        ssl_session_cache    shared:SSL:50m;
        ssl_session_timeout  5m;

        ssl_ciphers  HIGH:!aNULL:!MD5;
        ssl_prefer_server_ciphers  on;

        #access_log  logs/host.access.log  main;
        #access_log  "pipe:rollback logs/host.access_log interval=1d baknum=7 maxsize=2G"  main;

        location /db/ {
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_pass   http://127.0.0.1:8080/workspace/phpMyAdmin/;
            index  index.html index.htm;
        }
}

**Comment by razonklnbd** [comment]
hello developers,
i want to share my experience as i too face this problem.

history:
- installed php7.2 at ubuntu16
- old pma return count problem (see change log for php 7.2 http://php.net/manual/en/function.count.php)
- download and install pma latest stable version
- copy existing config.sample.inc.php to config.inc.php
- restart apache 2

everything fine as usual. logged in into pma, works fine. now next day i tried to login again and facing this problem. so i surfing the solution and come here and realize that problem is in cookie settings (probable) and in config.inc.php so, remove pma config.inc.php

and finally everything work normal as usual.

don' t know if it help someone!!! thanks.

**Comment by Zaczero** [comment]
Same issue here.
No idea what may be causing it but I'll leave some details which may be useful for you guys.

* url is https://pma.zaczero.pl
* nginx is listening on https only
* using cloudflare proxy
* ubuntu 18.04.2
* using latest phpmyadmin build (github master branch)
* using latest php build (https://launchpad.net/~ondrej/+archive/ubuntu/php/)

`config.inc.php`
![](https://i.imgur.com/8TSq7rE.png)

`nginx listen.conf`
![](https://i.imgur.com/vFD3ssO.png)

`nginx vhost.conf`
![](https://i.imgur.com/p4SjlBu.png)

---

I've also tried setting `$cfg['PmaAbsoluteUri'] = 'https://pma.zaczero.pl/'` but with no luck.

Maybe it's something with different HTTPS certificates between User-Cloudflare and Cloudflare-Server.
But I haven't had any issues for months ;;?
![](https://i.imgur.com/KMgf9qm.png)

**Comment by osc2nuke** [comment]
I figured out that chrome extensions can be a cause for this problem.
In my case it was the safe torrent scanner chrome extension.
Very interesting that such can produce a bug like this.
I do not think it is a phpMyAdmin issue.

**Comment by williamdes** [comment]
> I do not think it is a phpMyAdmin issue.

Trust me, it is

@osc2nuke Can you explain how to reproduce this issue from scratch using the extension that from what you said "can produce a bug like this."


Original comment: https://github.com/phpmyadmin/phpmyadmin/issues/14219#issuecomment-384737556

°1
----------
- Open a private navigation
- Login using HTTP
- Success !

°2
----------
- Open a private navigation
- Login using HTTPS
- Success !

°3
----------
1. Open a private navigation
2. Login using HTTPS
- Success
3. Login using HTTP
- Error !

**Comment by williamdes** [comment]
Original comment: https://github.com/phpmyadmin/phpmyadmin/issues/14219#issuecomment-384757638
As explained in https://security.stackexchange.com/a/140944
Secure Cookies are not sent by HTTP.
So if you first create the cookies on HTTPS you wont be able to send them to phpMyAdmin on HTTP.
They will be rewritten at each login, not sent back to the server.

**Comment by ibennetch** [comment]
There are many people here who have experienced this problem; can several of you try the pull request at https://github.com/phpmyadmin/phpmyadmin/pull/15273 to see if this fixes your problem?

**Comment by williamdes** [comment]
Just note that the PR #15273 will not solve the issue : the session expired and so the token is invalid when submitting the form, reloading and submitting the form another time fixes the issue

**Comment by williamdes** [comment]
I had `Safe Torrent Scanner` enabled on my Vivaldi and it created this issue everywhere ..
Disabled it.
Needs more investigation in the codebase of `Safe Torrent Scanner` (maybe reverse engineering needed here)

**Comment by rangka-kacang** [comment]
Hello.

I can't believe this is still not fix after a year. I asked about this issue last June and still looking for an answer.

https://stackoverflow.com/questions/50968326/failed-to-set-session-cookie-maybe-you-are-using-http-instead-of-https-to-acces

My hack at the moment is to simply not use `$cfg['Servers'][$i]['auth_type'] = 'cookie';` at all.

**Comment by Pantyboy** [comment]
I too have had this problem for over a year. I thought it would be rectified with each update but, here we are, 12 months on and still the problem exists.

I get around it by using Microsoft Edge. Why doesn't that have this problem?

**Comment by williamdes** [comment]
@Pantyboy what browser are you using and what extensions are enabled?

**Comment by nPHYN1T3** [comment]
I really wish the "which browser and which extensions" question would crawl in a ditch and die. I've tested this on virtually every browser you can list with and without extensions and the problem is always there. I have a VM with every browser still being actively worked on I can install all clean, no extensions, no tweaks or setting changes that I test things with.

I've also noticed a problem with how it redirects after login which makes me think it's got a path issue somewhere I've not been able to find. Either way the browser or extensions aren't the issue.

For funzies I've tested in Min, Firefox, Opera, Vivaldi, Chromium, Web, Midori and a few other derivatives/forks.

**Comment by williamdes** [comment]
@nPHYN1T3 okay, can you tell us more about your server setup? proxy?

**Comment by nPHYN1T3** [comment]
It's a server, no proxy...enlightening! Sorry dealing with so many technical issues lately I'm starting to get fed up. Not much to tell. All I can really say since I've forgot most of the things I've looked into or tried since this problem has persisted so long is that if I say make a fake domain in my hosts file on a client machine and a fake vhost for the pma folder it fails but when I log in again it redirects to the correct folder. If I say then access that same install from the path i.e. the machine ip/pmaFolder the https cookie still fails but upon logging in again it will redirect to the server root. Clearly something in the login routine is losing or doesn't understand it's path which could be part of the cause for the cookie to not be accessible. I wish I had more to say but again this has gone on so long I just gave up. I've forgot all the config tweaks, I just don't have time for this BS. I just keep logging into the idiotic thing. I have other projects and issues that are higher on the priority list. In fact I'm just accepting this is broken and muting the thread.

**Comment by Pantyboy** [comment]
@williamdes I using Firefox 68.0.1 (64bit). I'm using Apache 2.4.39 (Win64), php 7.3.7, MySQL 5.7.19 and phpmyadmin 4.9.0.1 on Windows 10 Home 64bit.

I have tried using Firefox (with and without extensions), Chrome (same). Both these browsers have the same issue. Internet Explorer and Edge do not.

phpmyadmin used to work on Firefox with extensions. What has happened in the last year?

My config.inc.php hasn't changed, nor has my httpd.conf and php.ini.

**Comment by PatientLearner** [comment]
I found this problem in Firefox 69 Dev and solutions that explained above doesn't work for me. I am using PHPMyAdmin 4.8.5 on WAMP Server localhost.

**Comment by apzentral** [comment]
> I figured out that chrome extensions can be a cause for this problem.
> In my case it was the safe torrent scanner chrome extension.
> Very interesting that such can produce a bug like this.
> I do not think it is a phpMyAdmin issue.

I also have the same issue. Once I turn off the "Safe Torrent Scanner" plugin, it now working again.

**Comment by williamdes** [comment]
Thanks to https://chrome.google.com/webstore/detail/chrome-extension-source-v/jifpbeccnghkjeaalbbjmodiffmgedin
Here is the source code of "Safe Torrent Scanner"
[aegnopegbbhjeeiganiajffnalhlkkjb.zip](https://github.com/phpmyadmin/phpmyadmin/files/3599315/aegnopegbbhjeeiganiajffnalhlkkjb.zip)

If someone finds what is wrong faster than me, post it here ;)

**Comment by rangka-kacang** [comment]
I've tested this just now and I can't produce it anymore. My environment are as follows (and is a fresh install, no extensions, nothing, just stock iso):
 
```
ubuntu@ubuntu:~$ uname -a
Linux ubuntu 5.0.0-27-generic #28~18.04.1-Ubuntu SMP Thu Aug 22 03:00:32 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
ubuntu@ubuntu:~$ lsb_release -d
Description:	Ubuntu 18.04.3 LTS
ubuntu@ubuntu:~$ mariadb -V
mariadb  Ver 15.1 Distrib 10.4.8-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
ubuntu@ubuntu:~$ nginx -v
nginx version: nginx/1.17.3
ubuntu@ubuntu:~$ php -v
PHP 7.3.9-1+ubuntu18.04.1+deb.sury.org+1 (cli) (built: Sep  2 2019 12:54:24) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.9, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.9-1+ubuntu18.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies
```

I have this on my `config.inc.php`:

```
<?php
$cfg['blowfish_secret'] = 'hidden';
$cfg['Servers'][1]['auth_type'] = 'cookie';
$cfg['Servers'][1]['host'] = 'localhost';
$cfg['Servers'][1]['compress'] = true;
$cfg['Servers'][1]['AllowNoPassword'] = false;
$cfg['Servers'][1]['controluser'] = 'hidden';
$cfg['Servers'][1]['controlpass'] = 'hidden';
$cfg['Servers'][1]['pmadb'] = 'phpmyadmin';
$cfg['Servers'][1]['bookmarktable'] = 'pma__bookmark';
$cfg['Servers'][1]['relation'] = 'pma__relation';
$cfg['Servers'][1]['table_info'] = 'pma__table_info';
$cfg['Servers'][1]['table_coords'] = 'pma__table_coords';
$cfg['Servers'][1]['pdf_pages'] = 'pma__pdf_pages';
$cfg['Servers'][1]['column_info'] = 'pma__column_info';
$cfg['Servers'][1]['history'] = 'pma__history';
$cfg['Servers'][1]['table_uiprefs'] = 'pma__table_uiprefs';
$cfg['Servers'][1]['tracking'] = 'pma__tracking';
$cfg['Servers'][1]['userconfig'] = 'pma__userconfig';
$cfg['Servers'][1]['recent'] = 'pma__recent';
$cfg['Servers'][1]['favorite'] = 'pma__favorite';
$cfg['Servers'][1]['users'] = 'pma__users';
$cfg['Servers'][1]['usergroups'] = 'pma__usergroups';
$cfg['Servers'][1]['navigationhiding'] = 'pma__navigationhiding';
$cfg['Servers'][1]['savedsearches'] = 'pma__savedsearches';
$cfg['Servers'][1]['central_columns'] = 'pma__central_columns';
$cfg['Servers'][1]['designer_settings'] = 'pma__designer_settings';
$cfg['Servers'][1]['export_templates'] = 'pma__export_templates';
$cfg['UploadDir'] = 'tmp';
$cfg['SaveDir'] = 'tmp';
$cfg['TempDir'] = 'tmp';
$cfg['ShowAll'] = true;
```

I have no problem accessing and logging in via localhost. I'm using phpMyAdmin 4.9.0.1 from https://files.phpmyadmin.net/phpMyAdmin/4.9.0.1/phpMyAdmin-4.9.0.1-all-languages.zip and Google Chrome Version 77.0.3865.75 (Official Build) (64-bit) from the official repository `deb [arch=amd64] https://dl.google.com/linux/chrome/deb stable main` -- Tested on both normal and incognito, no problem.

**Comment by dausruddin** [comment]
I am using squid proxy (latest) and phpmyadmin refusing to work on it.
Also when I left the tab for some time and it logged out, it will give the same error when I hit login button. Refreshing webpage seems to fix it, but I am hoping for a permanent solution.

**Comment by williamdes** [comment]
So this issue is now closed in next version, the unfixed (for now) part of this issue is #13172

Please, everybody that can do it:
Apply patch 21695cfeb743d62098abed74a9cceb79bec92560 (https://github.com/phpmyadmin/phpmyadmin/commit/21695cfeb743d62098abed74a9cceb79bec92560.patch)

And comment about if it works or not on your setup

**Comment by click0** [comment]
And how to apply this patch?

**Comment by ibennetch** [comment]
This fix was released as part of phpMyAdmin release 4.9.2. If you are able, please update to that version and let us know in this ticket if you continue to have trouble.

**Comment by williamdes** [comment]
```
wget https://github.com/phpmyadmin/phpmyadmin/commit/21695cfeb743d62098abed74a9cceb79bec92560.patch
git apply 21695cfeb743d62098abed74a9cceb79bec92560.patch
```

But the best option is still to update to 4.9.2

**Comment by Pantyboy** [comment]
I have just updated to 4.9.2 and it's made no difference. I'm still getting the same problem.

**Comment by click0** [comment]
Thanks.
Updating my problem solved.

**Comment by click0** [comment]
With the link https://example.com/phpmyadmin/ everything is ok.
In the case of a view link
https://example.com////phpmyadmin/
We get the error:
`Failed to set session cookie. Maybe you are using HTTP instead of HTTPS to access phpMyAdmin.`

**Comment by CallMarl** [comment]
Hello I upgrade phpmyadmin to 4.9.2 then the bug is style here.

**Comment by CallMarl** [comment]
> Hello I upgrade phpmyadmin to 4.9.2 then the bug is style here.

My url is: https://10.17.1.109:8443/index.php

**Comment by Btazbt** [comment]
using 4.9.2 and getting the same error. Tried using Chrome, IE, Firefox.  Running PHP Version 7.3.12 and MySQL version 8.0.18 with standard authentication.

```
Failed to set session cookie. Maybe you are using HTTP instead of HTTPS to access phpMyAdmin.
```

**Comment by williamdes** [comment]
For everyone that has  the issue using 4.9.2 and higher please post in #15634 
there is too much discussion here and some issues of this one are solved.
But not all the issues, still some edge cases to fix

**Comment by CallMarl** [comment]
Hey,
For me applying `4.9.2` didn't solve the mistake on Chrome but on Firefox. As I said previously in my config I have spécifique port and self-signed certificate.
I try new installation from the `git repo` not the `tar` then apply many différentes tag:
(I also try STABLE branch)

 - RELEASE_4_8_1
 - RELEASE_4_8_5
 - RELEASE_4_9_0
 - RELEASE_4_9_1
 - RELEASE_4_9_2
 
Finally work on Chrome `RELEASE_4_7_9`:

`git checkout tags/RELEASE_4_7_9`
`composer install --no-dev --optimize-autoloader -d /var/www/phpmyadmin`

#### If needed see my config:

##### Env
```Debian buster
php-7.3
php7.3-fpm
nginx/1.16.1
```

 - nginx_phpmyadmin.conf
```
upstream php-fpm-phpmyadmin{
	server	admin.slash16.local:9000;
}

server {
	listen 8443 ssl;
	listen [::]:8443 ssl;

	ssl_certificate /phpmyadmin.crt;
	ssl_certificate_key /phpmyadmin.key;

	server_name _;
	root /var/www/phpmyadmin/;
	index index.php;

	location / {
		rewrite ^.*$ /index.php;
	}

	location ~ \.(?:css|js|jpeg|jpg|gif|png|woff|woff2|ttf)$ {
		try_files $uri /$uri =404;
	}

	location ~ \.php$ {
		include snippets/fastcgi-php.conf;
		fastcgi_pass php-fpm-phpmyadmin;
	}

	location ~ /\.ht {
		deny all;
	}
}
```
 - fpm_phpmyadmin.conf
```
[phpmyadmin]

user = www-data
group = www-data

listen.owner = www-data
listen.group = www-data
listen = 0.0.0.0:9000

pm = dynamic
pm.max_children = 5
pm.start_servers = 2
pm.min_spare_servers = 1
pm.max_spare_servers = 3
```
 - config.inc.php
```
<?php
/* vim: set expandtab sw=4 ts=4 sts=4: */
/**
 * phpMyAdmin sample configuration, you can use it as base for
 * manual configuration. For easier setup you can use setup/
 *
 * All directives are explained in documentation in the doc/ folder
 * or at <https://docs.phpmyadmin.net/>.
 *
 * @package PhpMyAdmin
 */

/**
 * This is needed for cookie based authentication to encrypt password in
 * cookie. Needs to be 32 chars long.
 */                                         
$cfg['blowfish_secret'] = "111111111111111111111111111111111"; /* YOU MUST FILL IN THIS FOR COOKIE AUTH! */

/**
 * Servers configuration
 */
/**
 * First server
 */
$i = 1;
/* Server parameters */
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['host'] = 'db1.slash16.local';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['compress'] = false;
$cfg['Servers'][$i]['AllowNoPassword'] = false;
$cfg['Servers'][$i]['extension'] = 'mysql';

/**
 * Second server
 */
$i = 2;
/* Server parameters */
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['host'] = 'db2.slash16.local';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['compress'] = false;
$cfg['Servers'][$i]['AllowNoPassword'] = false;
$cfg['Servers'][$i]['extension'] = 'mysql';

/**
 * Third server
 */
$i = 3;
/* Server parameters */
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['host'] = 'preprod.slash16.local';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['compress'] = false;
$cfg['Servers'][$i]['AllowNoPassword'] = false;
$cfg['Servers'][$i]['extension'] = 'mysql';
```

**Comment by free4myself** [comment]
> > I figured out that chrome extensions can be a cause for this problem.
> > In my case it was the safe torrent scanner chrome extension.
> > Very interesting that such can produce a bug like this.
> > I do not think it is a phpMyAdmin issue.
> 
> I also have the same issue. Once I turn off the "Safe Torrent Scanner" plugin, it now working again.

In my case " Safe torrent scanner " chrome extension caused the login problem. So I disable it .

**Comment by Keagel** [comment]
In my case it was caused by the Firefox extension 'Disable HTML5 Autoplay'. Really weird.
