### ISSUE TITLE
processlist: show only active doesn't work

### ISSUE THREAD

**Issue by paveldvorak5** [phpmyadmin/phpmyadmin#14920]
### Describe the bug
When "show only active" checkbox is checked, it still shows sleeping connections. See image

### To Reproduce
Go to Status -> Processes
Click the show only active button

### Expected behavior

Hide sleeping conections

### Screenshots

![image](https://user-images.githubusercontent.com/14863835/51991247-fe3d9600-24aa-11e9-8c8d-01884b7d8ea3.png)

### Server configuration

Server type: MySQL
Server version: 5.7.23-log - MySQL Wsrep Server (GPL), wsrep_25.15
Protocol version: 10
Server charset: UTF-8 Unicode (utf8)

nginx/1.10.3
Database client version: libmysql - mysqlnd 5.0.12-dev - 20150407 - $Id: 38fea24f2847fa7519001be390c98ae0acafe387 $
PHP extension: mysqliDocumentation curlDocumentation mbstringDocumentation
PHP version: 7.2.11-2+0~20181015120801.9+stretch~1.gbp8105e0

Version information: 4.8.5 (up to date)

### Client configuration
Server issue

**Comment by williamdes** [comment]
See: #14800

**Comment by paveldvorak5** [comment]
OK. I though it's separate issue

**Comment by bahl24** [comment]
@paveldvorak5 @williamdes I couldn't reproduce the issue, I think it has been fixed. Kindly check

**Comment by williamdes** [comment]
@bahl24 @paveldvorak5 Could not reproduce this issue on latest `QA_4_8`.

**Comment by paveldvorak5** [comment]
It still doesn't work for me.
Server version: 5.7.23-log - MySQL Wsrep Server (GPL), wsrep_25.15
maybe wsrep is the problem?

**Comment by williamdes** [comment]
Fixed by 60564b5d923a371cf8a15ec34d010d4574f1dfbc
