### ISSUE TITLE
Cannot edit or export TIMESTAMP column with default CURRENT_TIMESTAMP in MySQL >= 8.0.13

### ISSUE THREAD

**Issue by domenk** [phpmyadmin/phpmyadmin#15315]
### Describe the bug

phpMyAdmin behaves weirdly when trying to edit or export TIMESTAMP column with default value of CURRENT_TIMESTAMP. It simply ignores the column if you try to edit it or export it.

### To Reproduce

1. Create a table with TIMESTAMP column (default should be CURRENT_TIMESTAMP):
```sql
CREATE TABLE `timestamp_test` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY(`id`)
);
```

2. Insert new row:
```sql
INSERT INTO `timestamp_test` (`id`) VALUES (NULL);
```

3a. Edit the row and change value of `timestamp` column. When saving, new value will be ignored.

3b. Export the table. CREATE TABLE will contain `timestamp` column, but exported rows won't – only `id` column will be exported.

### Expected behavior

You should be able to edit and export TIMESTAMP column.

### Server configuration

- Operating system: Windows
- Web server: Apache 2.4.39
- Database version: MySQL 8.0.16
- PHP version: 7.2.9 and 7.3.6
- phpMyAdmin version: 4.9.0.1

### Additional context

It looks like this issue appeared with MySQL 8.0.13. With MySQL 8.0.12 phpMyAdmin works as expected.

Culprit may be DEFAULT_GENERATED Extra property for columns with default value of CURRENT_TIMESTAMP that appeared in 8.0.13 but wasn't present in 8.0.12. Although [changelog for 8.0.13](https://dev.mysql.com/doc/relnotes/mysql/8.0/en/news-8-0-13.html) does not directly mention this change, it may be caused by the very last change in the changelog (bug #88619).

**Comment by williamdes** [comment]
@domenk Thanks for reporting !
```sql
SHOW COLUMNS FROM timestamp_test
```


Field | Type | Null | Key | Default | Extra |  
-- | -- | -- | -- | -- | -- | --
id | int(10) unsigned | NO | PRI | NULL | auto_increment
timestamp | timestamp | NO |   | CURRENT_TIMESTAMP | DEFAULT_GENERATED

**Comment by williamdes** [comment]
Fixed by 64dc20460ecf6688580f66063174012b75d0f66e

**Comment by toitzi** [comment]
@williamdes Can we reopen this? The problem still exists for me on two different servers.
Direct dump with `mysqldump` works as expected, just dumping over phpmyadmin does not work

### Server 1 configuration
Operating system: Ubuntu
Web server: Nginx/1.17.9
Database version: MySQL 8.0.19
PHP version: 7.4.3
phpMyAdmin version: 5.0.2

### Server 2 configuration
Operating system: Debian
Web server: Apache/2.4.38
Database version: MySQL 8.0.19
PHP version: 7.3.14
phpMyAdmin version: 4.9.4
