### ISSUE TITLE
phpMyAdmin5 HTTP HTTPS Error Behind Reverse PRoxy

### ISSUE THREAD

**Issue by fahadshery** [phpmyadmin/phpmyadmin#16035]
### Installation on FreeBSD

Server version: Apache/2.4.41 (FreeBSD)
mysql80-server-8.0.19
phpMyAdmin5-php72-5.0.1

### Describe the bug
I **can** access it locally i.e. directly via IP address (http://ip_address/phpmyadmin)

but getting the following error when accessing through a reverse proxy (nginx):
Failed to set session cookie. Maybe you are using HTTP instead of HTTPS to access phpMyAdmin.

I have a FQDN and my nginx is successfully proxying to other services/applications and taking care of the certificates etc..

I have checked your similar issues but nothing seems to be working.
any ideas?

**Comment by williamdes** [comment]
@fahadshery I would recommend you to try the latest version in development [(phpMyAdmin 5.0+snapshot)](https://www.phpmyadmin.net/downloads/)

**Comment by fahadshery** [comment]
thanks for your prompt response. I am even struggling to install the new one.
I was getting Forbidden and now Internall 500 error.
PS trying to access locally before trying to put it behind a reverse proxy.

Here are the exact steps to reproduce the error on a fresh install:
```bash
pkg install mysql80-server
sysrc mysql_enable=yes
service mysql-server start
mysql_secure_installation
pkg install apache24
sysrc apache24_enable=yes
service apache24 start
Set ServerName: vi /usr/local/etc/apache24/httpd.conf to localhost
service apache24 restart (no errors)
pkg install php72 php72-mysqli mod_php72 php72-mbstring php72-zlib php72-curl php72-gd php72-json

cp /usr/local/etc/php.ini{-production,}
rehash
vi /usr/local/etc/apache24/httpd.conf
```
add this at the end:
```bash
<FilesMatch "\.php$">
    SetHandler application/x-httpd-php
</FilesMatch>
<FilesMatch "\.phps$">
    SetHandler application/x-httpd-php-source
</FilesMatch>
```
Also in the same file find where 
```bash
<IfModule dir_module>
    DirectoryIndex index.html
</IfModule> 
```
and add index.php
```bash
service apache24 restart
pkg install wget
wget https://files.phpmyadmin.net/phpMyAdmin/5.0.1/phpMyAdmin-5.0.1-all-languages.tar.gz
tar xvf phpMyAdmin-5.0.1-all-languages.tar.gz
mv phpMyAdmin-5.0.1-all-languages /usr/local/www/apache24/data/phpmyadmin

add the following in the httpd.conf at the end:
Alias /phpmyadmin/ “/usr/local/www/apache24/data/phpMyAdmin/”
    <Directory “/usr/local/www/apache24/data/phpMyAdmin/”>
      AddDefaultCharset UTF-8
          <IfModule mod_authz_core.c>
                # Apache 2.4
                <RequireAny>
                        Require all granted
                </RequireAny>
        </IfModule>
        <IfModule !mod_authz_core.c>
                # Apache 2.2
                Order Allow,Deny
                Allow from All
        </IfModule>
        Options None
        AllowOverride Limit
        Require local
        Require host .example.com
    </Directory> 
```
this gets rid of the Forbidden error but introduces internal 500

**Comment by williamdes** [comment]
@fahadshery could you paste the error from php here so I can reproduce this issue more quickly ?

**Comment by fahadshery** [comment]
```
Failed to set session cookie. Maybe you are using HTTP instead of HTTPS to access phpMyAdmin.

```

**Comment by williamdes** [comment]
> I was getting Forbidden and now Internall 500 error.

So no more error 500 ?

**Comment by fahadshery** [comment]
sorry my bad... I have fixed the 500 error.
The `Failted to set session cookie`. still there.
[Here](https://fahadusman.com/install-mysql-8-phpmyadmin-python3-apache-in-freenas-11-3-jail-freebsd/) is how I fixed the internal 500 error.

**Comment by williamdes** [comment]
Hi @fahadshery  
Is the issue still there using the latest version?
