### ISSUE TITLE
Simple LEFT OUTER JOIN causes PHPMA error

### ISSUE THREAD

**Issue by NKarasek** [phpmyadmin/phpmyadmin#16059]
### Describe the bug

A vanilla LEFT OUTER JOIN causes big error in display functions.

### To Reproduce

1. Go to a database containing two related tables - Table A and Table B
2. Build an SQL query using a LEFT OUTER JOIN between the tables asking for ALL rows from Table A and matching rows from Table B.
3. Execute the Query
4. See error:
```
Fatal error: Uncaught TypeError: preg_match() expects parameter 2 to be string, null given in
libraries\classes\Display\Results.php:1804
Stack trace: #0
libraries\classes\Display\Results.php(1804): preg_match('@time|date@i', NULL) #1
libraries\classes\Display\Results.php(1695): PhpMyAdmin\Display\Results->_getSingleAndMultiSortUrls(Array, Array, '', NULL, Array, NULL) #2
libraries\classes\Display\Results.php(1103): PhpMyAdmin\Display\Results->_getOrderLinkAndSortedHeaderHtml(NULL, Array, Array, NULL, 'SELECT * \r\n ...', 50, '', Array, Array, NULL) #3
libraries\classes\Display\Results.php(1220): PhpMyAdmin\Display\Results->_getTableHeadersForColumns(Array, Array, Array, Array, Array, false, 'SELECT * \r\n ...') #4
libraries\classes\Display\Results.php(4292): PhpMyAdmin\Display\Results->_getTableHeaders(Array, Array, 'SELECT * \r\n **in
libraries\classes\Display\Results.php on line 1804
```

### Expected behavior
A normal execution and results display.

### Screenshots
Error detailed above

### Server configuration

- Operating system:  Win 10 Home with all recent updates

### Web Server
Apache/2.4.41 (Win64) OpenSSL/1.1.1c PHP/7.3.10
Database client version: libmysql - mysqlnd 5.0.12-dev - 20150407 - $Id: 7cc7cc96e675f6d72e5cf0f267f48e167c2abb23 $
PHP extension: mysqli Documentation curl Documentation mbstring Documentation
PHP version: 7.3.10

### Client configuration
- Browser:
Google Chrome 
Version 80.0.3987.162 (Official Build) (64-bit)

### Additional context
The Query described above executes correctly in command line MySQL (Maria) and in actual code included in the PHP application.
The same Query causes the error in PHPMA 5.0.1, 5.0.2, and 5.1.0 build date 3/22/2020

Possible reintroduction of error described in issue #11512

**Comment by Tithugues** [comment]
@williamdes , were you able to reproduce it please? I'm not able. Is there any link with date / time fields (based on error)?

@NKarasek , would it be please possible to provide a script with table creations and select that produces this error?

Thank you.

**Comment by williamdes** [comment]
Hi @Tithugues I did not have time to try to reproduce this issue, any help with issues assigned to milestones is very appreciated ;)
(I need some help to manage issues this month)

**Comment by williamdes** [comment]
@NKarasek Could you send the query ?
```sql
SELECT * FROM `data_in` LEFT OUTER JOIN data_in as b ON data_in.id = b.id
```
I had no errors

**Comment by williamdes** [comment]
_Could not reproduce, closing since no feedback or no way of reproducing was found.
Comment if you find a way to reproduce this issue, or want to re-open for a valid reason._

PS: I think this is fixed in 5.1 verions

**Comment by ChrisvanChip** [comment]
> @NKarasek Could you send the query ?
> 
> ```sql
> SELECT * FROM `data_in` LEFT OUTER JOIN data_in as b ON data_in.id = b.id
> ```
> 
> I had no errors

Hey! :wave:

This issue is still in the latest version of phpMyAdmin (5.1.1). The reproduction steps are still valid, this is an example of a built query:
![image](https://user-images.githubusercontent.com/31969757/150310742-69c25e2f-7dcd-421a-86a5-aa7439a30a99.png)

As you can see, there are 2+ tables used, which causes a LEFT JOIN to be applied. An example query that is built:
```sql
SELECT `Leden`.*, `Teams`.*
FROM `Teams`
    LEFT JOIN `Leden` ON `Leden`.`Lid van team` = `Teams`.`ID`
```

When executing the query using the "Submit query" button:
```
Fatal error: Uncaught TypeError: Argument 2 passed to PhpMyAdmin\DatabaseInterface::getColumns() must be of the type string, null given, called in 
/home/21v_chris/public_html/libraries/classes/Sql.php on line 189 and defined in /home/21v_chris/public_html/libraries/classes/DatabaseInterface.php:893 

Stack trace: #0 /home/21v_chris/public_html/libraries/classes/Sql.php(189): PhpMyAdmin\DatabaseInterface->getColumns('21v_chris_...', NULL) 
#1 /home/21v_chris/public_html/libraries/classes/Sql.php(1538): PhpMyAdmin\Sql->resultSetContainsUniqueKey('21v_chris_...', NULL, Array) 
#2 /home/21v_chris/public_html/libraries/classes/Sql.php(1858): PhpMyAdmin\Sql->getQueryResponseForResultsReturned(Object(mysqli_result), Array, '21v_chris_...', NULL, NULL, Object(PhpMyAdmin\Display\Results), './themes/pmahom...', 24, 24, NULL, NULL, NULL, 'SELECT `Leden`....', NULL) 
#3 /home/21v_chris/public_html/libraries/classes/Sql.php(1705): PhpMyAdmin\Sql->executeQueryAndGetQueryResponse(Array, false, '21 in /home/21v_chris/public_html/libraries/classes/DatabaseInterface.php on line 893
```

When copy-pasting the query to the SQL executor on the database, everything works as supposed. Possibly a button can be added to directly paste the generated query to the SQL executor? (as it would be amazing if this bug can be resolved as soon as possible)

I have done some surface-level debugging, and found out that the `$table` argument is empty in [/libraries/classes/DatabaseInterface.php.](https://github.com/phpmyadmin/phpmyadmin/blob/8fa99a33637ba2fc5f4a02a5781e270ddb8ae5e8/libraries/classes/Sql.php#L184)

**$db** -> 21v_chris_Sportclub_2
**$table** -> (empty)

Hopefully this helps you to find the cause! We would really appreciate it if it can be resolved quickly (and I'm available for elaborating/further reproduction)

**Comment by ChrisvanChip** [comment]
@williamdes As this issue was closed a year ago, here's a mention to let you know :)

**Comment by ChrisvanChip** [comment]
More information is in: the phpMyAdmin snapshot `phpMyAdmin-5.2+snapshot-all-languages.zip` resolved this issue already! 🎉 

So, basically the only thing we have to wait for, is an official release.
