### ISSUE TITLE
More actions is broken on table structure

### ISSUE THREAD

**Issue by liviuconcioiu** [phpmyadmin/phpmyadmin#17292]
### Describe the bug

More actions is broken when hovering the text on table structure. It affects only master.

### To Reproduce

1. Go to [https://demo.phpmyadmin.net/master/index.php?route=/table/structure&db=sakila&table=actor](https://demo.phpmyadmin.net/master/index.php?route=/table/structure&db=sakila&table=actor)
2. Click on `More`
3. See error

### Expected behavior

A menu should appear so other actions can be clicked.

### Server configuration

- Operating system:
- Web server:
- Database version:
- PHP version:
- phpMyAdmin version:

### Client configuration

- Browser:
- Operating system:

**Comment by williamdes** [comment]
I am going to close this issue as I can not reproduce it, I think it was fixed. Can you confirm @liviuconcioiu ?

**Comment by liviuconcioiu** [comment]
It isn't fixed.

Here is a video:

https://user-images.githubusercontent.com/25424343/152547601-344223c1-1983-4fd3-8fd3-2b8de461a412.mp4
