### ISSUE TITLE
on update CURRENT_TIMESTAMP doesn't show as default on attributes select

### ISSUE THREAD

**Issue by liviuconcioiu** [phpmyadmin/phpmyadmin#18276]
### Describe the bug

`on update CURRENT_TIMESTAMP` doesn't show as default on attributes select.

### To Reproduce

1. Have a column with `on update CURRENT_TIMESTAMP`
2. Edit that column
3. See the attribute not selected as default.

### Expected behavior

`on update CURRENT_TIMESTAMP` should be selected as default, if this attribute is present for that column.

### Screenshots

https://user-images.githubusercontent.com/25424343/226150476-c5b86263-89a0-4550-8f4b-2a770453d6bb.mp4

### Server configuration

- phpMyAdmin version: 5.2.2-dev, 6.0.0-dev

**Comment by sfurqan2** [comment]
I think this issue has been fixed, unable to reproduce it. @liviuconcioiu

**Comment by liviuconcioiu** [comment]
> I think this issue has been fixed, unable to reproduce it. @liviuconcioiu

Isn't fixed. Try and change `col`. You will see the attribute not selected.

```SQL
CREATE TABLE `test` (
  `id` int(11) NOT NULL,
  `col` timestamp NOT NULL ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
```

**Comment by sfurqan2** [comment]
Oh yes it is reproducing, I was trying it on MariaDb, my bad.
